#!/usr/bin/env python3
"""Writes shrine_data.rs, and copies Shrine's product photos in.

Upstream keeps the catalogue in `studies/shrine/model/products_repository.dart`
and the photographs in the `shrine_images` package, keyed by product id. Both
are read here rather than retyped, for the same reason the demo catalogue is
generated: thirty-eight hand-copied rows drift.
"""

import os
import re
import shutil

GALLERY = 'K:/flutter/dev/integration_tests/new_gallery/lib'
IMAGES = os.path.expandvars(
    r'$LOCALAPPDATA/Pub/Cache/hosted/pub.dev/shrine_images-2.0.2/lib')
HERE = 'K:/rustflutter/src/flutter/rust/examples/flutter_gallery'
OUT = HERE + '/src/shrine_data.rs'
ASSETS = HERE + '/assets/shrine'


def localized():
  text = open(GALLERY + '/gallery_localizations_en.dart', encoding='utf-8').read()
  out = {}
  for m in re.finditer(r"String get (\w+) =>\s*'((?:[^'\\]|\\.)*)'\s*;", text):
    out.setdefault(m.group(1), m.group(2).replace("\\'", "'"))
  return out


def products():
  strings = localized()
  src = open(GALLERY + '/studies/shrine/model/products_repository.dart',
             encoding='utf-8').read()
  found = []
  for block in src.split('Product(')[1:]:
    if '),' in block:
      block = block[:block.index('),')]
    category = re.search(r'category:\s*category(\w+)', block)
    pid = re.search(r'id:\s*(\d+)', block)
    name = re.search(r'GalleryLocalizations\.of\(context\)!\.(\w+)', block)
    price = re.search(r'price:\s*(\d+)', block)
    ratio = re.search(r'assetAspectRatio:\s*([0-9]+)\s*/\s*([0-9]+)', block)
    if not (category and pid and name and price):
      continue
    found.append({
        'id': int(pid.group(1)),
        'category': category.group(1),
        'name': strings.get(name.group(1), name.group(1)),
        'price': int(price.group(1)),
        'ratio': (int(ratio.group(1)) / int(ratio.group(2))) if ratio else 1.0,
    })
  return found


def main():
  items = products()
  os.makedirs(ASSETS, exist_ok=True)
  for item in items:
    name = '%d-0.jpg' % item['id']
    shutil.copyfile(os.path.join(IMAGES, name), os.path.join(ASSETS, name))

  categories = []
  for item in items:
    if item['category'] not in categories:
      categories.append(item['category'])

  lines = [
      '// Copyright 2013 The Flutter Authors. All rights reserved.',
      '// Use of this source code is governed by a BSD-style license that can be',
      '// found in the LICENSE file.',
      '',
      "//! Shrine's catalogue, generated by `tools/gen_shrine.py`.",
      '//!',
      '//! Names, prices, categories and aspect ratios come from upstream',
      "//! `studies/shrine/model/products_repository.dart`; the photographs come",
      '//! from the `shrine_images` package, keyed by product id, which is why the',
      '//! ids are kept rather than renumbered.',
      '//!',
      '//! Do not edit by hand.',
      '',
      '/// One thing for sale.',
      '#[derive(Clone, Copy, Debug)]',
      'pub struct Product {',
      '    pub id: u32,',
      "    pub name: &'static str,",
      '    pub price: u32,',
      '    pub category: Category,',
      "    /// Upstream's `assetAspectRatio`: the photograph's width over its",
      '    /// height. A tile that ignored it would letterbox or crop.',
      '    pub ratio: f32,',
      "    pub photo: &'static [u8],",
      '}',
      '',
      '#[derive(Clone, Copy, Debug, PartialEq, Eq)]',
      'pub enum Category {',
  ]
  for name in categories:
    lines.append('    %s,' % name)
  lines += [
      '}',
      '',
      'impl Category {',
      "    pub fn title(self) -> &'static str {",
      '        match self {',
  ]
  for name in categories:
    lines.append('            Category::%s => "%s",' % (name, name.upper()))
  lines += [
      '        }',
      '    }',
      '}',
      '',
      '/// The filter row, with "all" first the way upstream has it.',
      'pub const CATEGORIES: &[Option<Category>] = &[',
      '    None,',
  ]
  for name in categories:
    lines.append('    Some(Category::%s),' % name)
  lines += [
      '];',
      '',
      'pub const PRODUCTS: &[Product] = &[',
  ]
  for item in items:
    lines += [
        '    Product {',
        '        id: %d,' % item['id'],
        '        name: "%s",' % item['name'].replace('"', '\\"'),
        '        price: %d,' % item['price'],
        '        category: Category::%s,' % item['category'],
        '        ratio: %.4f,' % item['ratio'],
        '        photo: include_bytes!("../assets/shrine/%d-0.jpg"),' % item['id'],
        '    },',
    ]
  lines += [
      '];',
      '',
      '/// Everything in a category, or everything at all.',
      'pub fn in_category(category: Option<Category>) -> impl Iterator<Item = &\'static Product> {',
      '    PRODUCTS',
      '        .iter()',
      '        .filter(move |product| category.is_none_or(|c| product.category == c))',
      '}',
      '',
      '#[cfg(test)]',
      'mod tests {',
      '    use super::*;',
      '',
      '    #[test]',
      '    fn the_catalogue_matches_upstream() {',
      '        assert_eq!(PRODUCTS.len(), %d);' % len(items),
      '        // "All" plus one per category.',
      '        assert_eq!(CATEGORIES.len(), %d);' % (len(categories) + 1),
      '    }',
      '',
      '    #[test]',
      '    fn filtering_by_category_adds_back_up() {',
      '        let total: usize = CATEGORIES',
      '            .iter()',
      '            .skip(1)',
      '            .map(|c| in_category(*c).count())',
      '            .sum();',
      '        assert_eq!(total, PRODUCTS.len());',
      '        assert_eq!(in_category(None).count(), PRODUCTS.len());',
      '    }',
      '',
      '    #[test]',
      '    fn every_product_has_a_photo_and_a_shape() {',
      '        for product in PRODUCTS {',
      '            assert!(!product.photo.is_empty(), "{} has no photo", product.name);',
      '            assert!(product.ratio > 0.0, "{} has no aspect", product.name);',
      '        }',
      '    }',
      '}',
  ]

  open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
  print('wrote', OUT)
  print('products:', len(items), 'categories:', categories)


if __name__ == '__main__':
  main()
