// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! The Material colour palette, from upstream `material/colors.dart`.
//!
//! Two thousand lines of constants upstream, and the same constants here --
//! generated by parsing that file rather than typed out, because a palette
//! transcribed by hand is a palette with one wrong digit in it somewhere.
//!
//! A [`MaterialColor`] is a swatch: a primary colour and the ten shades
//! around it, keyed by weight. Upstream it is a `ColorSwatch<int>`, and it
//! *is* a `Color` as well -- `Colors.red` can be used where a colour is
//! wanted and means `Colors.red[500]`. There is no inheritance here, so a
//! swatch has [`MaterialColor::color`] and the shade accessors, and the
//! call site says which it wants.
//!
//! # Recorded divergences
//!
//! * Upstream's swatches are `ColorSwatch<int>` and indexable with `[]`.
//!   Here [`MaterialColor::shade`] takes the weight and answers an option,
//!   which is the same lookup with the missing case in the type.
//! * `Colors.primaries` and `Colors.accents` are the two lists upstream
//!   keeps for demos that walk the palette; they are here as
//!   [`Colors::PRIMARIES`] and [`Colors::ACCENTS`].

use crate::engine::Color;

/// Upstream `MaterialColor`: a primary colour and the shades around it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MaterialColor {
    /// The swatch's own colour -- upstream's `Color` half, which is the 500
    /// shade for a primary swatch and 200 for an accent one.
    pub color: Color,
    shades: [(u32, Color); MaterialColor::WIDEST],
    /// How many of `shades` are real; an accent swatch has four.
    count: usize,
}

impl MaterialColor {
    /// How many shades the widest swatch has -- upstream's `grey`, which
    /// carries a 350 and an 850 the others do not.
    pub const WIDEST: usize = 12;

    const fn new(
        color: Color,
        shades: [(u32, Color); MaterialColor::WIDEST],
        count: usize,
    ) -> MaterialColor {
        MaterialColor {
            color,
            shades,
            count,
        }
    }

    /// The shade at that weight, or `None` if the swatch has no such shade --
    /// upstream's `operator []`, which answers null the same way.
    pub fn shade(&self, weight: u32) -> Option<Color> {
        self.shades[..self.count]
            .iter()
            .find(|(at, _)| *at == weight)
            .map(|(_, colour)| *colour)
    }

    /// Every weight this swatch has, lightest first.
    pub fn weights(&self) -> impl Iterator<Item = u32> + '_ {
        self.shades[..self.count].iter().map(|(at, _)| *at)
    }
}

/// Upstream `MaterialAccentColor`: the four-shade accent swatch. The same
/// type here, since the only difference is which weights it has.
pub type MaterialAccentColor = MaterialColor;

/// Upstream `Colors`: the palette.
pub struct Colors;

impl Colors {
    /// Upstream `Colors.transparent`.
    pub const TRANSPARENT: Color = Color(0x00000000);

    /// Upstream `Colors.black`.
    pub const BLACK: Color = Color(0xff000000);

    /// Upstream `Colors.black87`.
    pub const BLACK87: Color = Color(0xdd000000);

    /// Upstream `Colors.black54`.
    pub const BLACK54: Color = Color(0x8a000000);

    /// Upstream `Colors.black45`.
    pub const BLACK45: Color = Color(0x73000000);

    /// Upstream `Colors.black38`.
    pub const BLACK38: Color = Color(0x61000000);

    /// Upstream `Colors.black26`.
    pub const BLACK26: Color = Color(0x42000000);

    /// Upstream `Colors.black12`.
    pub const BLACK12: Color = Color(0x1f000000);

    /// Upstream `Colors.white`.
    pub const WHITE: Color = Color(0xffffffff);

    /// Upstream `Colors.white70`.
    pub const WHITE70: Color = Color(0xb3ffffff);

    /// Upstream `Colors.white60`.
    pub const WHITE60: Color = Color(0x99ffffff);

    /// Upstream `Colors.white54`.
    pub const WHITE54: Color = Color(0x8affffff);

    /// Upstream `Colors.white38`.
    pub const WHITE38: Color = Color(0x62ffffff);

    /// Upstream `Colors.white30`.
    pub const WHITE30: Color = Color(0x4dffffff);

    /// Upstream `Colors.white24`.
    pub const WHITE24: Color = Color(0x3dffffff);

    /// Upstream `Colors.white12`.
    pub const WHITE12: Color = Color(0x1fffffff);

    /// Upstream `Colors.white10`.
    pub const WHITE10: Color = Color(0x1affffff);

    /// Upstream `Colors.red`.
    pub const RED: MaterialColor = MaterialColor::new(
        Color(0xfff44336),
        [
            (50, Color(0xffffebee)),
            (100, Color(0xffffcdd2)),
            (200, Color(0xffef9a9a)),
            (300, Color(0xffe57373)),
            (400, Color(0xffef5350)),
            (500, Color(0xfff44336)),
            (600, Color(0xffe53935)),
            (700, Color(0xffd32f2f)),
            (800, Color(0xffc62828)),
            (900, Color(0xffb71c1c)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.redAccent`.
    pub const RED_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffff5252),
        [
            (100, Color(0xffff8a80)),
            (200, Color(0xffff5252)),
            (400, Color(0xffff1744)),
            (700, Color(0xffd50000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.pink`.
    pub const PINK: MaterialColor = MaterialColor::new(
        Color(0xffe91e63),
        [
            (50, Color(0xfffce4ec)),
            (100, Color(0xfff8bbd0)),
            (200, Color(0xfff48fb1)),
            (300, Color(0xfff06292)),
            (400, Color(0xffec407a)),
            (500, Color(0xffe91e63)),
            (600, Color(0xffd81b60)),
            (700, Color(0xffc2185b)),
            (800, Color(0xffad1457)),
            (900, Color(0xff880e4f)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.pinkAccent`.
    pub const PINK_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffff4081),
        [
            (100, Color(0xffff80ab)),
            (200, Color(0xffff4081)),
            (400, Color(0xfff50057)),
            (700, Color(0xffc51162)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.purple`.
    pub const PURPLE: MaterialColor = MaterialColor::new(
        Color(0xff9c27b0),
        [
            (50, Color(0xfff3e5f5)),
            (100, Color(0xffe1bee7)),
            (200, Color(0xffce93d8)),
            (300, Color(0xffba68c8)),
            (400, Color(0xffab47bc)),
            (500, Color(0xff9c27b0)),
            (600, Color(0xff8e24aa)),
            (700, Color(0xff7b1fa2)),
            (800, Color(0xff6a1b9a)),
            (900, Color(0xff4a148c)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.purpleAccent`.
    pub const PURPLE_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffe040fb),
        [
            (100, Color(0xffea80fc)),
            (200, Color(0xffe040fb)),
            (400, Color(0xffd500f9)),
            (700, Color(0xffaa00ff)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.deepPurple`.
    pub const DEEP_PURPLE: MaterialColor = MaterialColor::new(
        Color(0xff673ab7),
        [
            (50, Color(0xffede7f6)),
            (100, Color(0xffd1c4e9)),
            (200, Color(0xffb39ddb)),
            (300, Color(0xff9575cd)),
            (400, Color(0xff7e57c2)),
            (500, Color(0xff673ab7)),
            (600, Color(0xff5e35b1)),
            (700, Color(0xff512da8)),
            (800, Color(0xff4527a0)),
            (900, Color(0xff311b92)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.deepPurpleAccent`.
    pub const DEEP_PURPLE_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xff7c4dff),
        [
            (100, Color(0xffb388ff)),
            (200, Color(0xff7c4dff)),
            (400, Color(0xff651fff)),
            (700, Color(0xff6200ea)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.indigo`.
    pub const INDIGO: MaterialColor = MaterialColor::new(
        Color(0xff3f51b5),
        [
            (50, Color(0xffe8eaf6)),
            (100, Color(0xffc5cae9)),
            (200, Color(0xff9fa8da)),
            (300, Color(0xff7986cb)),
            (400, Color(0xff5c6bc0)),
            (500, Color(0xff3f51b5)),
            (600, Color(0xff3949ab)),
            (700, Color(0xff303f9f)),
            (800, Color(0xff283593)),
            (900, Color(0xff1a237e)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.indigoAccent`.
    pub const INDIGO_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xff536dfe),
        [
            (100, Color(0xff8c9eff)),
            (200, Color(0xff536dfe)),
            (400, Color(0xff3d5afe)),
            (700, Color(0xff304ffe)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.blue`.
    pub const BLUE: MaterialColor = MaterialColor::new(
        Color(0xff2196f3),
        [
            (50, Color(0xffe3f2fd)),
            (100, Color(0xffbbdefb)),
            (200, Color(0xff90caf9)),
            (300, Color(0xff64b5f6)),
            (400, Color(0xff42a5f5)),
            (500, Color(0xff2196f3)),
            (600, Color(0xff1e88e5)),
            (700, Color(0xff1976d2)),
            (800, Color(0xff1565c0)),
            (900, Color(0xff0d47a1)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.blueAccent`.
    pub const BLUE_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xff448aff),
        [
            (100, Color(0xff82b1ff)),
            (200, Color(0xff448aff)),
            (400, Color(0xff2979ff)),
            (700, Color(0xff2962ff)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.lightBlue`.
    pub const LIGHT_BLUE: MaterialColor = MaterialColor::new(
        Color(0xff03a9f4),
        [
            (50, Color(0xffe1f5fe)),
            (100, Color(0xffb3e5fc)),
            (200, Color(0xff81d4fa)),
            (300, Color(0xff4fc3f7)),
            (400, Color(0xff29b6f6)),
            (500, Color(0xff03a9f4)),
            (600, Color(0xff039be5)),
            (700, Color(0xff0288d1)),
            (800, Color(0xff0277bd)),
            (900, Color(0xff01579b)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.lightBlueAccent`.
    pub const LIGHT_BLUE_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xff40c4ff),
        [
            (100, Color(0xff80d8ff)),
            (200, Color(0xff40c4ff)),
            (400, Color(0xff00b0ff)),
            (700, Color(0xff0091ea)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.cyan`.
    pub const CYAN: MaterialColor = MaterialColor::new(
        Color(0xff00bcd4),
        [
            (50, Color(0xffe0f7fa)),
            (100, Color(0xffb2ebf2)),
            (200, Color(0xff80deea)),
            (300, Color(0xff4dd0e1)),
            (400, Color(0xff26c6da)),
            (500, Color(0xff00bcd4)),
            (600, Color(0xff00acc1)),
            (700, Color(0xff0097a7)),
            (800, Color(0xff00838f)),
            (900, Color(0xff006064)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.cyanAccent`.
    pub const CYAN_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xff18ffff),
        [
            (100, Color(0xff84ffff)),
            (200, Color(0xff18ffff)),
            (400, Color(0xff00e5ff)),
            (700, Color(0xff00b8d4)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.teal`.
    pub const TEAL: MaterialColor = MaterialColor::new(
        Color(0xff009688),
        [
            (50, Color(0xffe0f2f1)),
            (100, Color(0xffb2dfdb)),
            (200, Color(0xff80cbc4)),
            (300, Color(0xff4db6ac)),
            (400, Color(0xff26a69a)),
            (500, Color(0xff009688)),
            (600, Color(0xff00897b)),
            (700, Color(0xff00796b)),
            (800, Color(0xff00695c)),
            (900, Color(0xff004d40)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.tealAccent`.
    pub const TEAL_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xff64ffda),
        [
            (100, Color(0xffa7ffeb)),
            (200, Color(0xff64ffda)),
            (400, Color(0xff1de9b6)),
            (700, Color(0xff00bfa5)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.green`.
    pub const GREEN: MaterialColor = MaterialColor::new(
        Color(0xff4caf50),
        [
            (50, Color(0xffe8f5e9)),
            (100, Color(0xffc8e6c9)),
            (200, Color(0xffa5d6a7)),
            (300, Color(0xff81c784)),
            (400, Color(0xff66bb6a)),
            (500, Color(0xff4caf50)),
            (600, Color(0xff43a047)),
            (700, Color(0xff388e3c)),
            (800, Color(0xff2e7d32)),
            (900, Color(0xff1b5e20)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.greenAccent`.
    pub const GREEN_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xff69f0ae),
        [
            (100, Color(0xffb9f6ca)),
            (200, Color(0xff69f0ae)),
            (400, Color(0xff00e676)),
            (700, Color(0xff00c853)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.lightGreen`.
    pub const LIGHT_GREEN: MaterialColor = MaterialColor::new(
        Color(0xff8bc34a),
        [
            (50, Color(0xfff1f8e9)),
            (100, Color(0xffdcedc8)),
            (200, Color(0xffc5e1a5)),
            (300, Color(0xffaed581)),
            (400, Color(0xff9ccc65)),
            (500, Color(0xff8bc34a)),
            (600, Color(0xff7cb342)),
            (700, Color(0xff689f38)),
            (800, Color(0xff558b2f)),
            (900, Color(0xff33691e)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.lightGreenAccent`.
    pub const LIGHT_GREEN_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffb2ff59),
        [
            (100, Color(0xffccff90)),
            (200, Color(0xffb2ff59)),
            (400, Color(0xff76ff03)),
            (700, Color(0xff64dd17)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.lime`.
    pub const LIME: MaterialColor = MaterialColor::new(
        Color(0xffcddc39),
        [
            (50, Color(0xfff9fbe7)),
            (100, Color(0xfff0f4c3)),
            (200, Color(0xffe6ee9c)),
            (300, Color(0xffdce775)),
            (400, Color(0xffd4e157)),
            (500, Color(0xffcddc39)),
            (600, Color(0xffc0ca33)),
            (700, Color(0xffafb42b)),
            (800, Color(0xff9e9d24)),
            (900, Color(0xff827717)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.limeAccent`.
    pub const LIME_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffeeff41),
        [
            (100, Color(0xfff4ff81)),
            (200, Color(0xffeeff41)),
            (400, Color(0xffc6ff00)),
            (700, Color(0xffaeea00)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.yellow`.
    pub const YELLOW: MaterialColor = MaterialColor::new(
        Color(0xffffeb3b),
        [
            (50, Color(0xfffffde7)),
            (100, Color(0xfffff9c4)),
            (200, Color(0xfffff59d)),
            (300, Color(0xfffff176)),
            (400, Color(0xffffee58)),
            (500, Color(0xffffeb3b)),
            (600, Color(0xfffdd835)),
            (700, Color(0xfffbc02d)),
            (800, Color(0xfff9a825)),
            (900, Color(0xfff57f17)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.yellowAccent`.
    pub const YELLOW_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffffff00),
        [
            (100, Color(0xffffff8d)),
            (200, Color(0xffffff00)),
            (400, Color(0xffffea00)),
            (700, Color(0xffffd600)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.amber`.
    pub const AMBER: MaterialColor = MaterialColor::new(
        Color(0xffffc107),
        [
            (50, Color(0xfffff8e1)),
            (100, Color(0xffffecb3)),
            (200, Color(0xffffe082)),
            (300, Color(0xffffd54f)),
            (400, Color(0xffffca28)),
            (500, Color(0xffffc107)),
            (600, Color(0xffffb300)),
            (700, Color(0xffffa000)),
            (800, Color(0xffff8f00)),
            (900, Color(0xffff6f00)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.amberAccent`.
    pub const AMBER_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffffd740),
        [
            (100, Color(0xffffe57f)),
            (200, Color(0xffffd740)),
            (400, Color(0xffffc400)),
            (700, Color(0xffffab00)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.orange`.
    pub const ORANGE: MaterialColor = MaterialColor::new(
        Color(0xffff9800),
        [
            (50, Color(0xfffff3e0)),
            (100, Color(0xffffe0b2)),
            (200, Color(0xffffcc80)),
            (300, Color(0xffffb74d)),
            (400, Color(0xffffa726)),
            (500, Color(0xffff9800)),
            (600, Color(0xfffb8c00)),
            (700, Color(0xfff57c00)),
            (800, Color(0xffef6c00)),
            (900, Color(0xffe65100)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.orangeAccent`.
    pub const ORANGE_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffffab40),
        [
            (100, Color(0xffffd180)),
            (200, Color(0xffffab40)),
            (400, Color(0xffff9100)),
            (700, Color(0xffff6d00)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.deepOrange`.
    pub const DEEP_ORANGE: MaterialColor = MaterialColor::new(
        Color(0xffff5722),
        [
            (50, Color(0xfffbe9e7)),
            (100, Color(0xffffccbc)),
            (200, Color(0xffffab91)),
            (300, Color(0xffff8a65)),
            (400, Color(0xffff7043)),
            (500, Color(0xffff5722)),
            (600, Color(0xfff4511e)),
            (700, Color(0xffe64a19)),
            (800, Color(0xffd84315)),
            (900, Color(0xffbf360c)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.deepOrangeAccent`.
    pub const DEEP_ORANGE_ACCENT: MaterialColor = MaterialColor::new(
        Color(0xffff6e40),
        [
            (100, Color(0xffff9e80)),
            (200, Color(0xffff6e40)),
            (400, Color(0xffff3d00)),
            (700, Color(0xffdd2c00)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        4,
    );

    /// Upstream `Colors.brown`.
    pub const BROWN: MaterialColor = MaterialColor::new(
        Color(0xff795548),
        [
            (50, Color(0xffefebe9)),
            (100, Color(0xffd7ccc8)),
            (200, Color(0xffbcaaa4)),
            (300, Color(0xffa1887f)),
            (400, Color(0xff8d6e63)),
            (500, Color(0xff795548)),
            (600, Color(0xff6d4c41)),
            (700, Color(0xff5d4037)),
            (800, Color(0xff4e342e)),
            (900, Color(0xff3e2723)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.grey`.
    pub const GREY: MaterialColor = MaterialColor::new(
        Color(0xff9e9e9e),
        [
            (50, Color(0xfffafafa)),
            (100, Color(0xfff5f5f5)),
            (200, Color(0xffeeeeee)),
            (300, Color(0xffe0e0e0)),
            (350, Color(0xffd6d6d6)),
            (400, Color(0xffbdbdbd)),
            (500, Color(0xff9e9e9e)),
            (600, Color(0xff757575)),
            (700, Color(0xff616161)),
            (800, Color(0xff424242)),
            (850, Color(0xff303030)),
            (900, Color(0xff212121)),
        ],
        12,
    );

    /// Upstream `Colors.blueGrey`.
    pub const BLUE_GREY: MaterialColor = MaterialColor::new(
        Color(0xff607d8b),
        [
            (50, Color(0xffeceff1)),
            (100, Color(0xffcfd8dc)),
            (200, Color(0xffb0bec5)),
            (300, Color(0xff90a4ae)),
            (400, Color(0xff78909c)),
            (500, Color(0xff607d8b)),
            (600, Color(0xff546e7a)),
            (700, Color(0xff455a64)),
            (800, Color(0xff37474f)),
            (900, Color(0xff263238)),
            (0, Color(0x00000000)),
            (0, Color(0x00000000)),
        ],
        10,
    );

    /// Upstream `Colors.primaries`: every primary swatch, in order.
    pub const PRIMARIES: [MaterialColor; 19] = [
        Colors::RED,
        Colors::PINK,
        Colors::PURPLE,
        Colors::DEEP_PURPLE,
        Colors::INDIGO,
        Colors::BLUE,
        Colors::LIGHT_BLUE,
        Colors::CYAN,
        Colors::TEAL,
        Colors::GREEN,
        Colors::LIGHT_GREEN,
        Colors::LIME,
        Colors::YELLOW,
        Colors::AMBER,
        Colors::ORANGE,
        Colors::DEEP_ORANGE,
        Colors::BROWN,
        Colors::GREY,
        Colors::BLUE_GREY,
    ];

    /// Upstream `Colors.accents`.
    pub const ACCENTS: [MaterialAccentColor; 16] = [
        Colors::RED_ACCENT,
        Colors::PINK_ACCENT,
        Colors::PURPLE_ACCENT,
        Colors::DEEP_PURPLE_ACCENT,
        Colors::INDIGO_ACCENT,
        Colors::BLUE_ACCENT,
        Colors::LIGHT_BLUE_ACCENT,
        Colors::CYAN_ACCENT,
        Colors::TEAL_ACCENT,
        Colors::GREEN_ACCENT,
        Colors::LIGHT_GREEN_ACCENT,
        Colors::LIME_ACCENT,
        Colors::YELLOW_ACCENT,
        Colors::AMBER_ACCENT,
        Colors::ORANGE_ACCENT,
        Colors::DEEP_ORANGE_ACCENT,
    ];
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_swatch_is_its_own_five_hundred() {
        // Upstream's `MaterialColor(_redPrimaryValue, ...)` and its 500 entry
        // are the same constant, which is what makes `Colors.red` usable
        // where a colour is wanted.
        assert_eq!(Colors::RED.color, Color(0xfff44336));
        assert_eq!(Colors::RED.shade(500), Some(Colors::RED.color));
        assert_eq!(Colors::RED.shade(50), Some(Color(0xffffebee)));
        assert_eq!(Colors::RED.shade(900), Some(Color(0xffb71c1c)));
        assert_eq!(Colors::RED.shade(250), None, "no such weight");
    }

    #[test]
    fn an_accent_swatch_has_four_shades_and_is_its_own_two_hundred() {
        assert_eq!(
            Colors::RED_ACCENT.weights().collect::<Vec<_>>(),
            vec![100, 200, 400, 700]
        );
        assert_eq!(
            Colors::RED_ACCENT.shade(200),
            Some(Colors::RED_ACCENT.color)
        );
        assert_eq!(Colors::RED_ACCENT.shade(500), None);
    }

    #[test]
    fn the_greys_and_the_transparencies_are_upstreams() {
        assert_eq!(Colors::TRANSPARENT, Color(0x00000000));
        assert_eq!(Colors::BLACK, Color(0xff000000));
        assert_eq!(Colors::BLACK54, Color(0x8a000000));
        assert_eq!(Colors::WHITE, Color(0xffffffff));
        assert_eq!(Colors::WHITE70, Color(0xb3ffffff));
        // Grey is a primary swatch, and its 500 is the one everything else
        // is measured against.
        assert_eq!(Colors::GREY.shade(500), Some(Colors::GREY.color));
    }

    #[test]
    fn every_primary_swatch_is_its_own_five_hundred_and_every_accent_its_two() {
        for swatch in Colors::PRIMARIES {
            // Ten weights, except grey, which carries a 350 and an 850 for
            // the raised button's pressed fill.
            assert!(matches!(swatch.weights().count(), 10 | 12));
            assert_eq!(swatch.shade(500), Some(swatch.color));
        }
        for swatch in Colors::ACCENTS {
            assert_eq!(swatch.weights().count(), 4);
            assert_eq!(swatch.shade(200), Some(swatch.color));
        }
        assert_eq!(Colors::GREY.weights().count(), 12);
        assert_eq!(Colors::GREY.shade(350), Some(Color(0xffd6d6d6)));
    }
}
