# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//flutter/rust/rustflutter_app.gni")

rustflutter_app("platform_channels") {
  sources = [
    "src/main.rs",
    "src/win32.rs",
    "src/android.rs",
    "src/linux.rs",
    "src/macos.rs",
  ]
}
