// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! Files written by `rustflutter create`.
//!
//! A generated project is an ordinary Cargo project that lives wherever its
//! author wants it, and builds with `cargo build`. It is not a GN target and
//! it is not inside this repository -- an application is not engine code, and
//! putting one in the engine tree makes every engine upgrade carry it.
//!
//! What makes that possible is `//flutter/rust:rustflutter_engine`, a single
//! archive holding the whole C++ side. The generated `build.rs` points rustc at
//! it and at nothing else; Cargo compiles the framework crate and the
//! application together and links against it.
//!
//! Kept as plain format strings rather than a template engine: a handful of
//! files and a handful of substitutions, and inlining them means `create` has
//! no dependency on anything outside std.

/// `Cargo.toml`. The framework is a path dependency on the checkout the CLI was
/// run from, which is also where the archive it links against is built.
pub fn cargo_toml(name: &str, framework: &str) -> String {
    format!(
        r#"# Generated by `rustflutter create {name}`.

[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
# The framework, by path. It is compiled from source along with this crate, so
# the application and the framework are one Rust compilation; what is linked in
# rather than compiled is the C++ engine underneath them -- see build.rs.
rustflutter = {{ path = "{framework}" }}

[features]
# Link the engine as a shared library -- rustflutter_engine.dll, .dylib or .so,
# copied next to the executable -- instead of folding its archive in.
#
#     cargo run                            the archive, inside the executable
#     cargo run --features shared-engine   the library, beside it
#     rustflutter run --shared             the same thing, spelled shorter
#
# The engine build produces both, always, so switching costs a link and nothing
# else. See build.rs for what each one means.
shared-engine = []

[profile.release]
# The engine is large and mostly untouched by the application, so the link is
# the slow part of a release build rather than the codegen.
codegen-units = 1
"#
    )
}

/// `.cargo/config.toml`. Both settings are about matching how the engine was
/// built, and both fail confusingly if they are missing.
pub fn cargo_config(linker: &str) -> String {
    format!(
        r#"# Generated by `rustflutter create`.

[build]
# The engine is built with /MT -- the static CRT -- so this has to be too.
# Without it the link fails on every CRT symbol being defined twice, once by
# msvcrt and once by the engine's libcmt.
rustflags = ["-C", "target-feature=+crt-static"]

[env]
# `cargo test` runs tests on a thread each, and a test that lays out a widget
# tree lays out text, which goes through the engine's txt / skparagraph stack.
# That stack is single-threaded by design -- upstream Flutter builds paragraphs
# only on the UI thread, and its shared FontCollection caches font families
# without a lock. Two tests shaping text at the same moment corrupt the heap and
# the process dies at exit, having reported every test as passed.
#
# So the tests are serialised here rather than in whoever remembers to type it.
RUST_TEST_THREADS = "1"

[target.x86_64-pc-windows-msvc]
# The engine's own linker, by absolute path. Under Git Bash a bare `link`
# resolves to coreutils' `link` rather than MSVC's linker, which fails with a
# baffling "extra operand" error.
linker = "{linker}"
"#
    )
}

/// `build.rs`: everything the application needs to know about the engine.
pub fn build_rs(out_dir: &str) -> String {
    format!(
        r#"// Generated by `rustflutter create`.
//
// Links the C++ engine and puts its ICU data where the executable will look for
// it. Nothing here knows about GN or ninja, and nothing here knows what the
// engine needs either: the engine build writes that down in
// `rustflutter_link.txt`, and this reads it.
//
// Which is the point of the file. The list used to live here, copied from the
// GN targets, and it rotted -- a library added to the engine reached this copy
// only if someone remembered. Now there is nothing to remember, and nothing to
// regenerate: a project created a year ago reads today's manifest.

use std::collections::HashMap;
use std::path::{{Path, PathBuf}};

/// The engine build directory. Override with RUSTFLUTTER_ENGINE_OUT to build
/// against a different configuration or a different checkout -- an Android or a
/// macOS output directory, say, rather than the host one this was created from.
const DEFAULT_ENGINE_OUT: &str = r"{out_dir}";

/// What the engine build says about itself.
const MANIFEST: &str = "rustflutter_link.txt";

fn main() {{
    let engine = std::env::var("RUSTFLUTTER_ENGINE_OUT")
        .unwrap_or_else(|_| DEFAULT_ENGINE_OUT.to_string());
    let engine = PathBuf::from(engine);

    println!("cargo:rerun-if-env-changed=RUSTFLUTTER_ENGINE_OUT");

    let manifest = Manifest::read(&engine);
    if shared() {{
        link_shared(&engine, &manifest);
    }} else {{
        link_static(&engine, &manifest);
    }}

    // The text stack loads this at startup and looks for it next to the
    // executable, so a `cargo run` has to find it there too.
    copy_beside_exe(&engine, "icudtl.dat");
}}

/// Which engine to link:
///
///     cargo build                            the archive, inside this binary
///     cargo build --features shared-engine   the library, beside it
///     rustflutter build --shared             the same thing, spelled shorter
///
/// Cargo sets `CARGO_FEATURE_<NAME>` for every enabled feature, which is how a
/// command-line option reaches a build script. Both artifacts are built by the
/// same `ninja`, so this is a decision about *this* application and nothing in
/// the engine has to be rebuilt to change it.
fn shared() -> bool {{
    std::env::var_os("CARGO_FEATURE_SHARED_ENGINE").is_some()
}}

/// The archive, folded into this executable. One file to ship and nothing to
/// find at startup, at the cost of carrying a copy of an engine this does not
/// modify.
fn link_static(engine: &Path, manifest: &Manifest) {{
    let archive = engine.join(manifest.value("archive"));
    require(&archive, engine, "flutter/rust:rustflutter_engine", "The engine archive");

    println!("cargo:rerun-if-changed={{}}", archive.display());
    println!(
        "cargo:rustc-link-search=native={{}}",
        archive.parent().unwrap().display()
    );
    println!(
        "cargo:rustc-link-lib=static={{}}",
        manifest.value("archive_link_name")
    );

    // What the engine's own link line asks for and an archive cannot carry:
    // Skia, the GL stack, the system text stack, the windowing system. A shared
    // library resolved all of these at its own link time, which is why they are
    // only named here.
    for name in manifest.all("lib") {{
        println!("cargo:rustc-link-lib=dylib={{name}}");
    }}
    for name in manifest.all("framework") {{
        println!("cargo:rustc-link-lib=framework={{name}}");
    }}
}}

/// The library, beside this executable. Applications in one directory share a
/// copy, and the link is a fraction of the work because the engine is already
/// linked -- which is most of a release link here.
fn link_shared(engine: &Path, manifest: &Manifest) {{
    let name = manifest.value("library");
    let library = engine.join(name);
    require(
        &library,
        engine,
        "flutter/rust:rustflutter_engine_shared",
        "The engine library",
    );

    println!("cargo:rerun-if-changed={{}}", library.display());
    println!("cargo:rustc-link-search=native={{}}", engine.display());
    println!(
        "cargo:rustc-link-lib=dylib={{}}",
        manifest.value("library_link_name")
    );

    // Where the loader is told to look, which every platform but Windows has to
    // be told. Windows searches beside the executable first.
    let rpath = manifest.value("library_rpath");
    if !rpath.is_empty() {{
        println!("cargo:rustc-link-arg=-Wl,-rpath,{{rpath}}");
    }}

    // So a `cargo run` finds it. Shipping is the same move: the library travels
    // with the application, and applications in one directory share it.
    copy_beside_exe(engine, name);
}}

/// `rustflutter_link.txt`, as the engine build wrote it.
///
/// `key = value` a line at a time, `#` to end of line a comment, and a key that
/// repeats -- `lib`, `framework` -- is a list. Parsed here rather than pulled in
/// as a dependency: it is fifteen lines, and a build script that needs a crate
/// to start is a build script that fails differently.
struct Manifest {{
    path: PathBuf,
    single: HashMap<String, String>,
    lists: HashMap<String, Vec<String>>,
}}

impl Manifest {{
    fn read(engine: &Path) -> Manifest {{
        let path = engine.join(MANIFEST);
        let Ok(text) = std::fs::read_to_string(&path) else {{
            panic!(
                "The engine build has not described itself:\n  {{}}\n\n\
                 Build it with:\n  ninja -C {{}} flutter/rust\n\n\
                 That writes what an application links -- both artifacts and \
                 the libraries the archive needs -- read off the engine's own \
                 link line. Set RUSTFLUTTER_ENGINE_OUT to point somewhere else.",
                path.display(),
                engine.display()
            );
        }};
        println!("cargo:rerun-if-changed={{}}", path.display());

        let mut single = HashMap::new();
        let mut lists: HashMap<String, Vec<String>> = HashMap::new();
        for line in text.lines() {{
            let line = line.split('#').next().unwrap_or("").trim();
            let Some((key, value)) = line.split_once('=') else {{
                continue;
            }};
            let (key, value) = (key.trim().to_string(), value.trim().to_string());
            if key == "lib" || key == "framework" {{
                lists.entry(key).or_default().push(value);
            }} else {{
                single.insert(key, value);
            }}
        }}
        Manifest {{ path, single, lists }}
    }}

    fn value(&self, key: &str) -> &str {{
        match self.single.get(key) {{
            Some(value) => value,
            // Not a missing entry so much as a manifest from a different
            // version of the engine, which is worth saying plainly.
            None => panic!("{{}} has no `{{key}}`.", self.path.display()),
        }}
    }}

    fn all(&self, key: &str) -> &[String] {{
        self.lists.get(key).map(Vec::as_slice).unwrap_or(&[])
    }}
}}

/// Stops with the command that produces `path`, rather than with a linker error
/// about a file nobody said had to exist.
fn require(path: &Path, engine: &Path, target: &str, what: &str) {{
    if path.exists() {{
        return;
    }}
    panic!(
        "{{what}} is not built:\n  {{}}\n\n\
         Build it with:\n  ninja -C {{}} {{target}}\n\n\
         It has to be a release build: everything is linked against the static \
         C runtime, which is what rustc uses, and a debug engine build uses the \
         debug one. Set RUSTFLUTTER_ENGINE_OUT to point somewhere else.",
        path.display(),
        engine.display()
    );
}}

/// Copies one of the engine's files beside the executable Cargo is about to
/// produce.
///
/// OUT_DIR is `<target>/<profile>/build/<crate>-<hash>/out`, so the executable's
/// directory is four levels up. Cargo exposes no direct variable for it.
fn copy_beside_exe(engine: &Path, name: &str) {{
    let Ok(out) = std::env::var("OUT_DIR") else {{ return }};
    let Some(exe_dir) = Path::new(&out).ancestors().nth(3) else {{ return }};
    let source = engine.join(name);
    if source.exists() {{
        let _ = std::fs::copy(&source, exe_dir.join(name));
    }}
}}
"#
    )
}

/// The starter app.
pub fn main_rs(name: &str, title: &str) -> String {
    format!(
        r##"// Generated by `rustflutter create {name}`.

use rustflutter::prelude::*;
use rustflutter::widgets::MainAxisSize;

const WIDTH: i32 = 800;
const HEIGHT: i32 = 600;

const BACKGROUND: Color = Color::rgb(0x0E, 0x16, 0x26);
const ACCENT: Color = Color::rgb(0x54, 0xC5, 0xF8);
const CARD: Color = Color::rgb(0x1B, 0x2A, 0x3A);

/// The application. The shell instantiates one and calls `build` every frame.
struct AppRoot;

impl Application for AppRoot {{
    fn background(&self) -> Color {{
        BACKGROUND
    }}

    /// Builds the widget tree. Constraints go down, sizes come up -- the same
    /// protocol as Flutter's RenderBox, so this should feel familiar.
    fn build(&mut self, _context: &BuildContext) -> BoxedWidget {{
        boxed(Center::new(
            Container::new()
                .with_color(CARD)
                .with_corner_radius(16.0)
                .with_padding(EdgeInsets::symmetric(48.0, 36.0))
                .with_child(
                    Column::new()
                        .with_main_axis_size(MainAxisSize::Min)
                        .with_spacing(12.0)
                        .push(
                            Text::new("{title}")
                                .with_size(52.0)
                                .with_weight(700)
                                .with_color(Color::WHITE)
                                .centered(),
                        )
                        .push(
                            Text::new("Built with rustflutter")
                                .with_size(20.0)
                                .with_color(ACCENT)
                                .centered(),
                        ),
                ),
        ))
    }}
}}

/// With no arguments this opens a window and hands control to the engine: from
/// there frames come from vsync, and each one runs
/// `Animator -> Engine -> RuntimeController -> Application::build`.
///
/// `--png <path>` renders a single frame headlessly instead, with no shell and
/// no window, which is handy for tests and CI.
fn main() -> std::process::ExitCode {{
    let args: Vec<String> = std::env::args().skip(1).collect();

    if let Some(path) = png_output(&args) {{
        return render_png(&path);
    }}

    register_application(|| Box::new(AppRoot));
    let options = RunOptions {{
        width: WIDTH,
        height: HEIGHT,
        title: String::from("{title}"),
        ..RunOptions::default()
    }};
    match run(&options) {{
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(code) => {{
            eprintln!("{name}: the host exited with {{code}}");
            std::process::ExitCode::FAILURE
        }}
    }}
}}

/// One frame, no shell, no window.
fn render_png(path: &str) -> std::process::ExitCode {{
    let app = App::new(WIDTH, HEIGHT).with_background(BACKGROUND);
    let mut root = AppRoot;
    let context = BuildContext {{
        view_id: 0,
        size: Size::new(WIDTH as f32, HEIGHT as f32),
        metrics: Default::default(),
        frame_number: 1,
        frame_time_micros: 0,
        scheduler: Default::default(),
    }};
    match app.render_to_png(root.build(&context), path) {{
        Ok(()) => {{
            println!("{name}: wrote {{path}} ({{WIDTH}}x{{HEIGHT}})");
            std::process::ExitCode::SUCCESS
        }}
        Err(err) => {{
            eprintln!("{name}: render failed: {{err}}");
            std::process::ExitCode::FAILURE
        }}
    }}
}}

/// Returns the path for `--png <path>`, defaulting the path if it is omitted.
fn png_output(args: &[String]) -> Option<String> {{
    let index = args.iter().position(|a| a == "--png")?;
    Some(
        args.get(index + 1)
            .cloned()
            .unwrap_or_else(|| "{name}.png".to_string()),
    )
}}
"##
    )
}

pub fn gitignore() -> &'static str {
    "/target\n"
}

pub fn readme(name: &str, engine_out: &str) -> String {
    format!(
        r#"# {name}

Generated by `rustflutter create {name}`. An ordinary Cargo project: it is not
part of the rustflutter repository and not a GN target.

```sh
cargo run                 # opens a window, frames driven by vsync
cargo run -- --png {name}.png    # one frame, headless
cargo test
```

## How it links

The Flutter engine is C++ and is built with GN, so it cannot be a Cargo
dependency. Instead the engine build produces it twice -- an archive and a
library -- and this project links whichever you ask for:

```sh
cd <checkout>/src
vpython3 flutter/tools/gn --runtime-mode=release --no-rbe
ninja -C out/host_release flutter/rust                # both artifacts
```

```sh
cargo run                             # static: the engine, inside the executable
cargo run --features shared-engine    # shared: the engine library, beside it
rustflutter run --shared              # the same thing, spelled shorter
```

Static is the default and needs nothing at runtime, at the cost of an executable
with a whole engine in it. Shared links in a fraction of the time and lets
applications in one directory share one copy, which `build.rs` puts next to the
executable -- ship the two together. Nothing has to be rebuilt to switch: both
artifacts are always there, and the feature picks.

`build.rs` finds them under

```
{engine_out}
```

and copies `icudtl.dat` next to the executable either way. Set
`RUSTFLUTTER_ENGINE_OUT` to build against a different checkout or
configuration.

It has to be a **release** engine build. Everything is linked with the static
CRT (`/MT`), which is what rustc uses, and a debug engine build uses `/MTd`
instead; mixing them fails with every CRT symbol defined twice.

`src/main.rs` holds the whole app. The UI is built from `rustflutter`'s widget
layer -- `Center`, `Container`, `Column`, `Text` -- which lays out with the same
constraints-down / sizes-up protocol as Flutter's `RenderBox`, then paints into
an engine `DisplayList`. Rendering, text shaping and compositing are the Flutter
engine's own C++; only the framework above it is Rust.
"#
    )
}
