// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! Files written by `rustflutter create`.
//!
//! Kept as plain format strings rather than a template engine: there are four
//! files and two substitutions, and inlining them means `create` has no
//! dependency on anything outside std.

/// `BUILD.gn` for a generated app.
pub fn build_gn(name: &str) -> String {
    format!(
        r#"# Generated by `rustflutter create {name}`.

# The app itself. Rust, compiled to a staticlib so it links with the C++ engine.
static_library("{name}_rs") {{
  crate_name = "{name}"
  crate_root = "src/main.rs"

  sources = [ "src/main.rs" ]

  deps = [ "//flutter/rust/rustflutter" ]
}}

executable("{name}") {{
  sources = [ "main.cc" ]

  deps = [
    ":{name}_rs",
    "//flutter/rust/ffi:engine_ffi",
    "//flutter/rust/host",
  ]

  if (is_win) {{
    # Pulled in by the Rust standard library.
    libs = [
      "advapi32.lib",
      "bcrypt.lib",
      "ntdll.lib",
      "userenv.lib",
      "ws2_32.lib",
    ]
  }}
}}
"#
    )
}

/// The C++ shim entry point. Identical for every app, so it is not templated.
pub const MAIN_CC: &str = r#"// Generated by `rustflutter create`.
//
// The executable is C++ because the engine it links against is C++; the app
// itself lives entirely in Rust. This file exists only to hand argc/argv to
// rustflutter_app_main and should not grow.

extern "C" int rustflutter_app_main(int argc, const char** argv);

int main(int argc, const char** argv) {
  return rustflutter_app_main(argc, argv);
}
"#;

/// The starter app.
pub fn main_rs(name: &str, title: &str) -> String {
    format!(
        r##"// Generated by `rustflutter create {name}`.

use std::os::raw::{{c_char, c_int}};

use rustflutter::prelude::*;

const WIDTH: i32 = 800;
const HEIGHT: i32 = 600;

const BACKGROUND: Color = Color::rgb(0x0E, 0x16, 0x26);
const ACCENT: Color = Color::rgb(0x54, 0xC5, 0xF8);
const CARD: Color = Color::rgb(0x1B, 0x2A, 0x3A);

/// The application. The shell instantiates one and calls `build` every frame.
struct AppRoot;

impl Application for AppRoot {{
    fn background(&self) -> Color {{
        BACKGROUND
    }}

    /// Builds the widget tree. Constraints go down, sizes come up -- the same
    /// protocol as Flutter's RenderBox, so this should feel familiar.
    fn build(&mut self, _context: &BuildContext) -> BoxedWidget {{
        Box::new(Center::new(
            Container::new()
                .with_color(CARD)
                .with_corner_radius(16.0)
                .with_padding(EdgeInsets::symmetric(48.0, 36.0))
                .with_child(
                    Column::new()
                        .with_spacing(12.0)
                        .push(
                            Text::new("{title}")
                                .with_size(52.0)
                                .with_weight(700)
                                .with_color(Color::WHITE)
                                .centered(),
                        )
                        .push(
                            Text::new("Built with rustflutter")
                                .with_size(20.0)
                                .with_color(ACCENT)
                                .centered(),
                        ),
                ),
        ))
    }}
}}

/// Entry point, called by the C++ shim in main.cc.
///
/// With no arguments this opens a window and hands control to the engine: from
/// there frames come from vsync, and each one runs
/// `Animator -> Engine -> RuntimeController -> Application::build`.
///
/// `--png <path>` renders a single frame headlessly instead, with no shell and
/// no window, which is handy for tests and CI.
#[unsafe(no_mangle)]
pub extern "C" fn rustflutter_app_main(argc: c_int, argv: *const *const c_char) -> c_int {{
    let args = collect_args(argc, argv);

    if let Some(path) = png_output(&args) {{
        return render_png(&path);
    }}

    register_application(|| Box::new(AppRoot));
    let options = RunOptions {{
        width: WIDTH,
        height: HEIGHT,
        title: String::from("{title}"),
        ..RunOptions::default()
    }};
    match run(&options) {{
        Ok(()) => 0,
        Err(code) => {{
            eprintln!("{name}: the host exited with {{code}}");
            1
        }}
    }}
}}

/// One frame, no shell, no window.
fn render_png(path: &str) -> c_int {{
    let app = App::new(WIDTH, HEIGHT).with_background(BACKGROUND);
    let mut root = AppRoot;
    let context = BuildContext {{
        view_id: 0,
        size: Size::new(WIDTH as f32, HEIGHT as f32),
        metrics: Default::default(),
        frame_number: 1,
        frame_time_micros: 0,
        scheduler: Default::default(),
    }};
    match app.render_to_png(root.build(&context), path) {{
        Ok(()) => {{
            println!("{name}: wrote {{path}} ({{WIDTH}}x{{HEIGHT}})");
            0
        }}
        Err(err) => {{
            eprintln!("{name}: render failed: {{err}}");
            1
        }}
    }}
}}

/// Returns the path for `--png <path>`, defaulting the path if it is omitted.
fn png_output(args: &[String]) -> Option<String> {{
    let index = args.iter().position(|a| a == "--png")?;
    Some(
        args.get(index + 1)
            .cloned()
            .unwrap_or_else(|| "{name}.png".to_string()),
    )
}}

fn collect_args(argc: c_int, argv: *const *const c_char) -> Vec<String> {{
    if argv.is_null() || argc <= 1 {{
        return Vec::new();
    }}
    // SAFETY: the C++ shim passes main()'s argc/argv unchanged, so argv holds
    // at least `argc` NUL-terminated pointers.
    (1..argc as usize)
        .filter_map(|i| unsafe {{
            let ptr = *argv.add(i);
            if ptr.is_null() {{
                None
            }} else {{
                std::ffi::CStr::from_ptr(ptr).to_str().ok().map(str::to_string)
            }}
        }})
        .collect()
}}
"##
    )
}

pub fn readme(name: &str) -> String {
    format!(
        r#"# {name}

Generated by `rustflutter create {name}`.

```sh
rustflutter run {name}
```

That builds the app with ninja and opens a window showing it. Add
`-- --png {name}.png` to render one frame headlessly instead.

`src/main.rs` holds the whole app; `main.cc` is a fixed three-line shim that
hands `argc`/`argv` to the Rust entry point and should not need editing.

The UI is built from `rustflutter`'s widget layer -- `Center`, `Container`,
`Column`, `Text` -- which lays out with the same constraints-down /
sizes-up protocol as Flutter's `RenderBox`, then paints into an engine
`DisplayList`. Rendering, text shaping and compositing are the Flutter engine's
own C++; only the framework above it is Rust.
"#
    )
}

/// The group that ties every project into the build.
pub fn projects_group(deps: &str) -> String {
    format!(
        r#"# Generated by `rustflutter create`. Edited automatically -- to add a project,
# run `rustflutter create <name>` rather than editing this file.

group("projects") {{
  deps = [
{deps}  ]
}}
"#
    )
}
