// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! Files written by `rustflutter create`.
//!
//! A generated project is an ordinary Cargo project that lives wherever its
//! author wants it, and builds with `cargo build`. It is not a GN target and
//! it is not inside this repository -- an application is not engine code, and
//! putting one in the engine tree makes every engine upgrade carry it.
//!
//! What makes that possible is `//flutter/rust:rustflutter_engine`, a single
//! archive holding the whole C++ side. The generated `build.rs` points rustc at
//! it and at nothing else; Cargo compiles the framework crate and the
//! application together and links against it.
//!
//! Kept as plain format strings rather than a template engine: a handful of
//! files and a handful of substitutions, and inlining them means `create` has
//! no dependency on anything outside std.

/// `Cargo.toml`. The framework is a path dependency on the checkout the CLI was
/// run from, which is also where the archive it links against is built.
pub fn cargo_toml(name: &str, framework: &str) -> String {
    format!(
        r#"# Generated by `rustflutter create {name}`.

[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
# The framework, by path. It is compiled from source along with this crate, so
# the application and the framework are one Rust compilation; what is linked in
# rather than compiled is the C++ engine underneath them -- see build.rs.
rustflutter = {{ path = "{framework}" }}

[profile.release]
# The engine is large and mostly untouched by the application, so the link is
# the slow part of a release build rather than the codegen.
codegen-units = 1
"#
    )
}

/// `.cargo/config.toml`. Both settings are about matching how the engine was
/// built, and both fail confusingly if they are missing.
pub fn cargo_config(linker: &str) -> String {
    format!(
        r#"# Generated by `rustflutter create`.

[build]
# The engine is built with /MT -- the static CRT -- so this has to be too.
# Without it the link fails on every CRT symbol being defined twice, once by
# msvcrt and once by the engine's libcmt.
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
# The engine's own linker, by absolute path. Under Git Bash a bare `link`
# resolves to coreutils' `link` rather than MSVC's linker, which fails with a
# baffling "extra operand" error.
linker = "{linker}"
"#
    )
}

/// `build.rs`: everything the application needs to know about the engine.
pub fn build_rs(out_dir: &str) -> String {
    format!(
        r#"// Generated by `rustflutter create`.
//
// Links the C++ engine and puts its ICU data where the executable will look for
// it. Nothing here knows about GN or ninja: the engine build produces one
// archive, and this points rustc at it.

use std::path::{{Path, PathBuf}};

/// The engine build directory. Override with RUSTFLUTTER_ENGINE_OUT to build
/// against a different configuration or a different checkout.
const DEFAULT_ENGINE_OUT: &str = r"{out_dir}";

fn main() {{
    let engine = std::env::var("RUSTFLUTTER_ENGINE_OUT")
        .unwrap_or_else(|_| DEFAULT_ENGINE_OUT.to_string());
    let engine = PathBuf::from(engine);

    let archive = engine.join("obj/flutter/rust/rustflutter_engine.lib");
    if !archive.exists() {{
        panic!(
            "the engine archive is not built:\n  {{}}\n\n\
             Build it with:\n  \
             ninja -C {{}} flutter/rust:rustflutter_engine\n\n\
             It has to be a /MT configuration -- a release build -- because \
             rustc links the static CRT. Set RUSTFLUTTER_ENGINE_OUT to point \
             somewhere else.",
            archive.display(),
            engine.display()
        );
    }}

    println!("cargo:rerun-if-changed={{}}", archive.display());
    println!("cargo:rerun-if-env-changed=RUSTFLUTTER_ENGINE_OUT");
    println!(
        "cargo:rustc-link-search=native={{}}",
        engine.join("obj/flutter/rust").display()
    );
    println!("cargo:rustc-link-lib=static=rustflutter_engine");

    // What the engine's own link line asks for. Rust's standard library brings
    // the first few; the rest are Skia, ANGLE, DirectWrite and the shell.
    for lib in [
        "advapi32", "bcrypt", "ntdll", "userenv", "ws2_32", "comdlg32",
        "delayimp", "dnsapi", "iphlpapi", "msimg32", "odbc32", "odbccp32",
        "ole32", "oleaut32", "psapi", "shell32", "shlwapi", "Rpcrt4", "uuid",
        "version", "wininet", "winmm", "winspool", "gdi32", "user32",
        "FontSub", "Usp10", "OpenGL32", "dwmapi", "synchronization",
        "setupapi", "dxgi", "dxguid", "windowscodecs",
    ] {{
        println!("cargo:rustc-link-lib=dylib={{lib}}");
    }}

    // The text stack loads this at startup and looks for it next to the
    // executable, so a `cargo run` has to find it there too.
    copy_icu(&engine);
}}

/// Copies `icudtl.dat` beside the executable Cargo is about to produce.
///
/// OUT_DIR is `<target>/<profile>/build/<crate>-<hash>/out`, so the executable's
/// directory is four levels up. Cargo exposes no direct variable for it.
fn copy_icu(engine: &Path) {{
    let Ok(out) = std::env::var("OUT_DIR") else {{ return }};
    let Some(exe_dir) = Path::new(&out).ancestors().nth(3) else {{ return }};
    let source = engine.join("icudtl.dat");
    let destination = exe_dir.join("icudtl.dat");
    if source.exists() {{
        let _ = std::fs::copy(&source, &destination);
    }}
}}
"#
    )
}

/// The starter app.
pub fn main_rs(name: &str, title: &str) -> String {
    format!(
        r##"// Generated by `rustflutter create {name}`.

use rustflutter::prelude::*;

const WIDTH: i32 = 800;
const HEIGHT: i32 = 600;

const BACKGROUND: Color = Color::rgb(0x0E, 0x16, 0x26);
const ACCENT: Color = Color::rgb(0x54, 0xC5, 0xF8);
const CARD: Color = Color::rgb(0x1B, 0x2A, 0x3A);

/// The application. The shell instantiates one and calls `build` every frame.
struct AppRoot;

impl Application for AppRoot {{
    fn background(&self) -> Color {{
        BACKGROUND
    }}

    /// Builds the widget tree. Constraints go down, sizes come up -- the same
    /// protocol as Flutter's RenderBox, so this should feel familiar.
    fn build(&mut self, _context: &BuildContext) -> BoxedWidget {{
        Box::new(Center::new(
            Container::new()
                .with_color(CARD)
                .with_corner_radius(16.0)
                .with_padding(EdgeInsets::symmetric(48.0, 36.0))
                .with_child(
                    Column::new()
                        .with_spacing(12.0)
                        .push(
                            Text::new("{title}")
                                .with_size(52.0)
                                .with_weight(700)
                                .with_color(Color::WHITE)
                                .centered(),
                        )
                        .push(
                            Text::new("Built with rustflutter")
                                .with_size(20.0)
                                .with_color(ACCENT)
                                .centered(),
                        ),
                ),
        ))
    }}
}}

/// With no arguments this opens a window and hands control to the engine: from
/// there frames come from vsync, and each one runs
/// `Animator -> Engine -> RuntimeController -> Application::build`.
///
/// `--png <path>` renders a single frame headlessly instead, with no shell and
/// no window, which is handy for tests and CI.
fn main() -> std::process::ExitCode {{
    let args: Vec<String> = std::env::args().skip(1).collect();

    if let Some(path) = png_output(&args) {{
        return render_png(&path);
    }}

    register_application(|| Box::new(AppRoot));
    let options = RunOptions {{
        width: WIDTH,
        height: HEIGHT,
        title: String::from("{title}"),
        ..RunOptions::default()
    }};
    match run(&options) {{
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(code) => {{
            eprintln!("{name}: the host exited with {{code}}");
            std::process::ExitCode::FAILURE
        }}
    }}
}}

/// One frame, no shell, no window.
fn render_png(path: &str) -> std::process::ExitCode {{
    let app = App::new(WIDTH, HEIGHT).with_background(BACKGROUND);
    let mut root = AppRoot;
    let context = BuildContext {{
        view_id: 0,
        size: Size::new(WIDTH as f32, HEIGHT as f32),
        metrics: Default::default(),
        frame_number: 1,
        frame_time_micros: 0,
        scheduler: Default::default(),
    }};
    match app.render_to_png(root.build(&context), path) {{
        Ok(()) => {{
            println!("{name}: wrote {{path}} ({{WIDTH}}x{{HEIGHT}})");
            std::process::ExitCode::SUCCESS
        }}
        Err(err) => {{
            eprintln!("{name}: render failed: {{err}}");
            std::process::ExitCode::FAILURE
        }}
    }}
}}

/// Returns the path for `--png <path>`, defaulting the path if it is omitted.
fn png_output(args: &[String]) -> Option<String> {{
    let index = args.iter().position(|a| a == "--png")?;
    Some(
        args.get(index + 1)
            .cloned()
            .unwrap_or_else(|| "{name}.png".to_string()),
    )
}}
"##
    )
}

pub fn gitignore() -> &'static str {
    "/target\n"
}

pub fn readme(name: &str, engine_out: &str) -> String {
    format!(
        r#"# {name}

Generated by `rustflutter create {name}`. An ordinary Cargo project: it is not
part of the rustflutter repository and not a GN target.

```sh
cargo run                 # opens a window, frames driven by vsync
cargo run -- --png {name}.png    # one frame, headless
cargo test
```

## How it links

The Flutter engine is C++ and is built with GN, so it cannot be a Cargo
dependency. Instead the engine build produces one archive holding all of it:

```sh
cd <checkout>/src
vpython3 flutter/tools/gn --runtime-mode=release --no-rbe
ninja -C out/host_release flutter/rust:rustflutter_engine
```

`build.rs` points rustc at that archive -- currently

```
{engine_out}
```

-- and copies `icudtl.dat` next to the executable. Set `RUSTFLUTTER_ENGINE_OUT`
to build against a different checkout or configuration.

It has to be a **release** engine build. Everything is linked with the static
CRT (`/MT`), which is what rustc uses, and a debug engine build uses `/MTd`
instead; mixing them fails with every CRT symbol defined twice.

`src/main.rs` holds the whole app. The UI is built from `rustflutter`'s widget
layer -- `Center`, `Container`, `Column`, `Text` -- which lays out with the same
constraints-down / sizes-up protocol as Flutter's `RenderBox`, then paints into
an engine `DisplayList`. Rendering, text shaping and compositing are the Flutter
engine's own C++; only the framework above it is Rust.
"#
    )
}
