// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! The translations for English (`en`).
//!
//! Upstream `lib/l10n/gallery_localizations_en.dart` (flutter/gallery @
//! d12640d), class `GalleryLocalizationsEn`. Generated by
//! `tools/gen_l10n.py`; do not edit by hand. The regional subclasses
//! upstream keeps in the same file (`GalleryLocalizationsEnAu` and
//! friends) are not part of the table: their strings are English too,
//! and the port is English-only per PORTING.md.

/// Upstream's `GalleryLocalizationsEn`. Zero-sized: every member is a
/// method, so the value only ever exists to be reached through
/// `super::gallery_localizations::GalleryLocalizations`'s `Deref`.
pub struct GalleryLocalizationsEn;

impl GalleryLocalizationsEn {
    pub fn github_repo(&self, repo_name: impl std::fmt::Display) -> String {
        format!("{repo_name} GitHub repository")
    }
    pub fn about_dialog_description(&self, repo_link: impl std::fmt::Display) -> String {
        format!("To see the source code for this app, please visit the {repo_link}.")
    }
    pub fn deselect(&self) -> &'static str {
        "Deselect"
    }
    pub fn not_selected(&self) -> &'static str {
        "Not selected"
    }
    pub fn select(&self) -> &'static str {
        "Select"
    }
    pub fn selectable(&self) -> &'static str {
        "Selectable (long press)"
    }
    pub fn selected(&self) -> &'static str {
        "Selected"
    }
    pub fn sign_in(&self) -> &'static str {
        "SIGN IN"
    }
    pub fn banner_demo_text(&self) -> &'static str {
        "Your password was updated on your other device. Please sign in \
                      again."
    }
    pub fn banner_demo_reset_text(&self) -> &'static str {
        "Reset the banner"
    }
    pub fn banner_demo_multiple_text(&self) -> &'static str {
        "Multiple actions"
    }
    pub fn banner_demo_leading_text(&self) -> &'static str {
        "Leading Icon"
    }
    pub fn dismiss(&self) -> &'static str {
        "DISMISS"
    }
    pub fn back_to_gallery(&self) -> &'static str {
        "Back to Gallery"
    }
    pub fn cards_demo_explore(&self) -> &'static str {
        "Explore"
    }
    pub fn cards_demo_explore_semantics(&self, destination_name: impl std::fmt::Display) -> String {
        format!("Explore {destination_name}")
    }
    pub fn cards_demo_share_semantics(&self, destination_name: impl std::fmt::Display) -> String {
        format!("Share {destination_name}")
    }
    pub fn cards_demo_tappable(&self) -> &'static str {
        "Tappable"
    }
    pub fn cards_demo_travel_destination_title1(&self) -> &'static str {
        "Top 10 Cities to Visit in Tamil Nadu"
    }
    pub fn cards_demo_travel_destination_description1(&self) -> &'static str {
        "Number 10"
    }
    pub fn cards_demo_travel_destination_city1(&self) -> &'static str {
        "Thanjavur"
    }
    pub fn cards_demo_travel_destination_location1(&self) -> &'static str {
        "Thanjavur, Tamil Nadu"
    }
    pub fn cards_demo_travel_destination_title2(&self) -> &'static str {
        "Artisans of Southern India"
    }
    pub fn cards_demo_travel_destination_description2(&self) -> &'static str {
        "Silk Spinners"
    }
    pub fn cards_demo_travel_destination_city2(&self) -> &'static str {
        "Chettinad"
    }
    pub fn cards_demo_travel_destination_location2(&self) -> &'static str {
        "Sivaganga, Tamil Nadu"
    }
    pub fn cards_demo_travel_destination_title3(&self) -> &'static str {
        "Brihadisvara Temple"
    }
    pub fn cards_demo_travel_destination_description3(&self) -> &'static str {
        "Temples"
    }
    pub fn home_header_gallery(&self) -> &'static str {
        "Gallery"
    }
    pub fn home_header_categories(&self) -> &'static str {
        "Categories"
    }
    pub fn shrine_description(&self) -> &'static str {
        "A fashionable retail app"
    }
    pub fn fortnightly_description(&self) -> &'static str {
        "A content-focused news app"
    }
    pub fn rally_description(&self) -> &'static str {
        "A personal finance app"
    }
    pub fn reply_description(&self) -> &'static str {
        "An efficient, focused email app"
    }
    pub fn rally_account_data_checking(&self) -> &'static str {
        "Checking"
    }
    pub fn rally_account_data_home_savings(&self) -> &'static str {
        "Home Savings"
    }
    pub fn rally_account_data_car_savings(&self) -> &'static str {
        "Car Savings"
    }
    pub fn rally_account_data_vacation(&self) -> &'static str {
        "Vacation"
    }
    pub fn rally_account_detail_data_annual_percentage_yield(&self) -> &'static str {
        "Annual Percentage Yield"
    }
    pub fn rally_account_detail_data_interest_rate(&self) -> &'static str {
        "Interest Rate"
    }
    pub fn rally_account_detail_data_interest_ytd(&self) -> &'static str {
        "Interest YTD"
    }
    pub fn rally_account_detail_data_interest_paid_last_year(&self) -> &'static str {
        "Interest Paid Last Year"
    }
    pub fn rally_account_detail_data_next_statement(&self) -> &'static str {
        "Next Statement"
    }
    pub fn rally_account_detail_data_account_owner(&self) -> &'static str {
        "Account Owner"
    }
    pub fn rally_bill_detail_total_amount(&self) -> &'static str {
        "Total Amount"
    }
    pub fn rally_bill_detail_amount_paid(&self) -> &'static str {
        "Amount Paid"
    }
    pub fn rally_bill_detail_amount_due(&self) -> &'static str {
        "Amount Due"
    }
    pub fn rally_budget_category_coffee_shops(&self) -> &'static str {
        "Coffee Shops"
    }
    pub fn rally_budget_category_groceries(&self) -> &'static str {
        "Groceries"
    }
    pub fn rally_budget_category_restaurants(&self) -> &'static str {
        "Restaurants"
    }
    pub fn rally_budget_category_clothing(&self) -> &'static str {
        "Clothing"
    }
    pub fn rally_budget_detail_total_cap(&self) -> &'static str {
        "Total Cap"
    }
    pub fn rally_budget_detail_amount_used(&self) -> &'static str {
        "Amount Used"
    }
    pub fn rally_budget_detail_amount_left(&self) -> &'static str {
        "Amount Left"
    }
    pub fn rally_settings_manage_accounts(&self) -> &'static str {
        "Manage Accounts"
    }
    pub fn rally_settings_tax_documents(&self) -> &'static str {
        "Tax Documents"
    }
    pub fn rally_settings_passcode_and_touch_id(&self) -> &'static str {
        "Passcode and Touch ID"
    }
    pub fn rally_settings_notifications(&self) -> &'static str {
        "Notifications"
    }
    pub fn rally_settings_personal_information(&self) -> &'static str {
        "Personal Information"
    }
    pub fn rally_settings_paperless_settings(&self) -> &'static str {
        "Paperless Settings"
    }
    pub fn rally_settings_find_atms(&self) -> &'static str {
        "Find ATMs"
    }
    pub fn rally_settings_help(&self) -> &'static str {
        "Help"
    }
    pub fn rally_settings_sign_out(&self) -> &'static str {
        "Sign out"
    }
    pub fn rally_account_total(&self) -> &'static str {
        "Total"
    }
    pub fn rally_bills_due(&self) -> &'static str {
        "Due"
    }
    pub fn rally_budget_left(&self) -> &'static str {
        "Left"
    }
    pub fn rally_accounts(&self) -> &'static str {
        "Accounts"
    }
    pub fn rally_bills(&self) -> &'static str {
        "Bills"
    }
    pub fn rally_budgets(&self) -> &'static str {
        "Budgets"
    }
    pub fn rally_alerts(&self) -> &'static str {
        "Alerts"
    }
    pub fn rally_see_all(&self) -> &'static str {
        "SEE ALL"
    }
    pub fn rally_finance_left(&self) -> &'static str {
        " LEFT"
    }
    pub fn rally_title_overview(&self) -> &'static str {
        "OVERVIEW"
    }
    pub fn rally_title_accounts(&self) -> &'static str {
        "ACCOUNTS"
    }
    pub fn rally_title_bills(&self) -> &'static str {
        "BILLS"
    }
    pub fn rally_title_budgets(&self) -> &'static str {
        "BUDGETS"
    }
    pub fn rally_title_settings(&self) -> &'static str {
        "SETTINGS"
    }
    pub fn rally_login_login_to_rally(&self) -> &'static str {
        "Login to Rally"
    }
    pub fn rally_login_no_account(&self) -> &'static str {
        "Don't have an account?"
    }
    pub fn rally_login_sign_up(&self) -> &'static str {
        "SIGN UP"
    }
    pub fn rally_login_username(&self) -> &'static str {
        "Username"
    }
    pub fn rally_login_password(&self) -> &'static str {
        "Password"
    }
    pub fn rally_login_label_login(&self) -> &'static str {
        "Login"
    }
    pub fn rally_login_remember_me(&self) -> &'static str {
        "Remember Me"
    }
    pub fn rally_login_button_login(&self) -> &'static str {
        "LOGIN"
    }
    pub fn rally_alerts_message_heads_up_shopping(
        &self,
        percent: impl std::fmt::Display,
    ) -> String {
        format!("Heads up, you've used up {percent} of your Shopping budget for this month.")
    }
    pub fn rally_alerts_message_spent_on_restaurants(
        &self,
        amount: impl std::fmt::Display,
    ) -> String {
        format!("You've spent {amount} on Restaurants this week.")
    }
    pub fn rally_alerts_message_atm_fees(&self, amount: impl std::fmt::Display) -> String {
        format!("You've spent {amount} in ATM fees this month")
    }
    pub fn rally_alerts_message_checking_account(&self, percent: impl std::fmt::Display) -> String {
        format!("Good work! Your checking account is {percent} higher than last month.")
    }
    pub fn rally_alerts_message_unassigned_transactions(&self, count: i64) -> String {
        if count == 1 {
            "Increase your potential tax deduction! Assign categories to 1 \
                      unassigned transaction."
                .to_string()
        } else {
            format!("Increase your potential tax deduction! Assign categories to {count} unassigned transactions.")
        }
    }
    pub fn rally_see_all_accounts(&self) -> &'static str {
        "See all accounts"
    }
    pub fn rally_see_all_bills(&self) -> &'static str {
        "See all bills"
    }
    pub fn rally_see_all_budgets(&self) -> &'static str {
        "See all budgets"
    }
    pub fn rally_account_amount(
        &self,
        account_name: impl std::fmt::Display,
        account_number: impl std::fmt::Display,
        amount: impl std::fmt::Display,
    ) -> String {
        format!("{account_name} account {account_number} with {amount}.")
    }
    pub fn rally_bill_amount(
        &self,
        bill_name: impl std::fmt::Display,
        date: impl std::fmt::Display,
        amount: impl std::fmt::Display,
    ) -> String {
        format!("{bill_name} bill due {date} for {amount}.")
    }
    pub fn rally_budget_amount(
        &self,
        budget_name: impl std::fmt::Display,
        amount_used: impl std::fmt::Display,
        amount_total: impl std::fmt::Display,
        amount_left: impl std::fmt::Display,
    ) -> String {
        format!(
            "{budget_name} budget with {amount_used} used of {amount_total}, {amount_left} left"
        )
    }
    pub fn crane_description(&self) -> &'static str {
        "A personalized travel app"
    }
    pub fn home_category_reference(&self) -> &'static str {
        "STYLES & OTHER"
    }
    pub fn demo_invalid_url(&self) -> &'static str {
        "Couldn't display URL:"
    }
    pub fn demo_options_tooltip(&self) -> &'static str {
        "Options"
    }
    pub fn demo_info_tooltip(&self) -> &'static str {
        "Info"
    }
    pub fn demo_code_tooltip(&self) -> &'static str {
        "Demo Code"
    }
    pub fn demo_documentation_tooltip(&self) -> &'static str {
        "API Documentation"
    }
    pub fn demo_fullscreen_tooltip(&self) -> &'static str {
        "Full Screen"
    }
    pub fn demo_code_viewer_copy_all(&self) -> &'static str {
        "COPY ALL"
    }
    pub fn demo_code_viewer_copied_to_clipboard_message(&self) -> &'static str {
        "Copied to clipboard."
    }
    pub fn demo_code_viewer_failed_to_copy_to_clipboard_message(
        &self,
        error: impl std::fmt::Display,
    ) -> String {
        format!("Failed to copy to clipboard: {error}")
    }
    pub fn demo_options_feature_title(&self) -> &'static str {
        "View options"
    }
    pub fn demo_options_feature_description(&self) -> &'static str {
        "Tap here to view available options for this demo."
    }
    pub fn settings_title(&self) -> &'static str {
        "Settings"
    }
    pub fn settings_button_label(&self) -> &'static str {
        "Settings"
    }
    pub fn settings_button_close_label(&self) -> &'static str {
        "Close settings"
    }
    pub fn settings_system_default(&self) -> &'static str {
        "System"
    }
    pub fn settings_text_scaling(&self) -> &'static str {
        "Text scaling"
    }
    pub fn settings_text_scaling_small(&self) -> &'static str {
        "Small"
    }
    pub fn settings_text_scaling_normal(&self) -> &'static str {
        "Normal"
    }
    pub fn settings_text_scaling_large(&self) -> &'static str {
        "Large"
    }
    pub fn settings_text_scaling_huge(&self) -> &'static str {
        "Huge"
    }
    pub fn settings_text_direction(&self) -> &'static str {
        "Text direction"
    }
    pub fn settings_text_direction_locale_based(&self) -> &'static str {
        "Based on locale"
    }
    pub fn settings_text_direction_ltr(&self) -> &'static str {
        "LTR"
    }
    pub fn settings_text_direction_rtl(&self) -> &'static str {
        "RTL"
    }
    pub fn settings_locale(&self) -> &'static str {
        "Locale"
    }
    pub fn settings_platform_mechanics(&self) -> &'static str {
        "Platform mechanics"
    }
    pub fn settings_theme(&self) -> &'static str {
        "Theme"
    }
    pub fn settings_dark_theme(&self) -> &'static str {
        "Dark"
    }
    pub fn settings_light_theme(&self) -> &'static str {
        "Light"
    }
    pub fn settings_slow_motion(&self) -> &'static str {
        "Slow motion"
    }
    pub fn settings_about(&self) -> &'static str {
        "About Flutter Gallery"
    }
    pub fn settings_feedback(&self) -> &'static str {
        "Send feedback"
    }
    pub fn settings_attribution(&self) -> &'static str {
        "Designed by TOASTER in London"
    }
    pub fn demo_app_bar_title(&self) -> &'static str {
        "App bar"
    }
    pub fn demo_app_bar_subtitle(&self) -> &'static str {
        "Displays information and actions relating to the current \
                      screen"
    }
    pub fn demo_app_bar_description(&self) -> &'static str {
        "The App bar provides content and actions related to the \
                      current screen. It's used for branding, screen titles, \
                      navigation, and actions"
    }
    pub fn demo_bottom_app_bar_title(&self) -> &'static str {
        "Bottom app bar"
    }
    pub fn demo_bottom_app_bar_subtitle(&self) -> &'static str {
        "Displays navigation and actions at the bottom"
    }
    pub fn demo_bottom_app_bar_description(&self) -> &'static str {
        "Bottom app bars provide access to a bottom navigation drawer \
                      and up to four actions, including the floating action button."
    }
    pub fn bottom_app_bar_notch(&self) -> &'static str {
        "Notch"
    }
    pub fn bottom_app_bar_position(&self) -> &'static str {
        "Floating Action Button Position"
    }
    pub fn bottom_app_bar_position_docked_end(&self) -> &'static str {
        "Docked - End"
    }
    pub fn bottom_app_bar_position_docked_center(&self) -> &'static str {
        "Docked - Center"
    }
    pub fn bottom_app_bar_position_floating_end(&self) -> &'static str {
        "Floating - End"
    }
    pub fn bottom_app_bar_position_floating_center(&self) -> &'static str {
        "Floating - Center"
    }
    pub fn demo_banner_title(&self) -> &'static str {
        "Banner"
    }
    pub fn demo_banner_subtitle(&self) -> &'static str {
        "Displaying a banner within a list"
    }
    pub fn demo_banner_description(&self) -> &'static str {
        "A banner displays an important, succinct message, and provides \
                      actions for users to address (or dismiss the banner). A user \
                      action is required for it to be dismissed."
    }
    pub fn demo_bottom_navigation_title(&self) -> &'static str {
        "Bottom navigation"
    }
    pub fn demo_bottom_navigation_subtitle(&self) -> &'static str {
        "Bottom navigation with cross-fading views"
    }
    pub fn demo_bottom_navigation_persistent_labels(&self) -> &'static str {
        "Persistent labels"
    }
    pub fn demo_bottom_navigation_selected_label(&self) -> &'static str {
        "Selected label"
    }
    pub fn demo_bottom_navigation_description(&self) -> &'static str {
        "Bottom navigation bars display three to five destinations at \
                      the bottom of a screen. Each destination is represented by an \
                      icon and an optional text label. When a bottom navigation icon \
                      is tapped, the user is taken to the top-level navigation \
                      destination associated with that icon."
    }
    pub fn demo_button_title(&self) -> &'static str {
        "Buttons"
    }
    pub fn demo_button_subtitle(&self) -> &'static str {
        "Text, elevated, outlined, and more"
    }
    pub fn demo_text_button_title(&self) -> &'static str {
        "Text Button"
    }
    pub fn demo_text_button_description(&self) -> &'static str {
        "A text button displays an ink splash on press but does not \
                      lift. Use text buttons on toolbars, in dialogs and inline with \
                      padding"
    }
    pub fn demo_elevated_button_title(&self) -> &'static str {
        "Elevated Button"
    }
    pub fn demo_elevated_button_description(&self) -> &'static str {
        "Elevated buttons add dimension to mostly flat layouts. They \
                      emphasize functions on busy or wide spaces."
    }
    pub fn demo_outlined_button_title(&self) -> &'static str {
        "Outlined Button"
    }
    pub fn demo_outlined_button_description(&self) -> &'static str {
        "Outlined buttons become opaque and elevate when pressed. They \
                      are often paired with raised buttons to indicate an \
                      alternative, secondary action."
    }
    pub fn demo_toggle_button_title(&self) -> &'static str {
        "Toggle Buttons"
    }
    pub fn demo_toggle_button_description(&self) -> &'static str {
        "Toggle buttons can be used to group related options. To \
                      emphasize groups of related toggle buttons, a group should \
                      share a common container"
    }
    pub fn demo_floating_button_title(&self) -> &'static str {
        "Floating Action Button"
    }
    pub fn demo_floating_button_description(&self) -> &'static str {
        "A floating action button is a circular icon button that hovers \
                      over content to promote a primary action in the application."
    }
    pub fn demo_card_title(&self) -> &'static str {
        "Cards"
    }
    pub fn demo_card_subtitle(&self) -> &'static str {
        "Baseline cards with rounded corners"
    }
    pub fn demo_chip_title(&self) -> &'static str {
        "Chips"
    }
    pub fn demo_card_description(&self) -> &'static str {
        "A card is a sheet of Material used to represent some related \
                      information, for example an album, a geographical location, a \
                      meal, contact details, etc."
    }
    pub fn demo_chip_subtitle(&self) -> &'static str {
        "Compact elements that represent an input, attribute, or action"
    }
    pub fn demo_action_chip_title(&self) -> &'static str {
        "Action Chip"
    }
    pub fn demo_action_chip_description(&self) -> &'static str {
        "Action chips are a set of options which trigger an action \
                      related to primary content. Action chips should appear \
                      dynamically and contextually in a UI."
    }
    pub fn demo_choice_chip_title(&self) -> &'static str {
        "Choice Chip"
    }
    pub fn demo_choice_chip_description(&self) -> &'static str {
        "Choice chips represent a single choice from a set. Choice \
                      chips contain related descriptive text or categories."
    }
    pub fn demo_filter_chip_title(&self) -> &'static str {
        "Filter Chip"
    }
    pub fn demo_filter_chip_description(&self) -> &'static str {
        "Filter chips use tags or descriptive words as a way to filter \
                      content."
    }
    pub fn demo_input_chip_title(&self) -> &'static str {
        "Input Chip"
    }
    pub fn demo_input_chip_description(&self) -> &'static str {
        "Input chips represent a complex piece of information, such as \
                      an entity (person, place, or thing) or conversational text, in \
                      a compact form."
    }
    pub fn demo_data_table_title(&self) -> &'static str {
        "Data Tables"
    }
    pub fn demo_data_table_subtitle(&self) -> &'static str {
        "Rows and columns of information"
    }
    pub fn demo_data_table_description(&self) -> &'static str {
        "Data tables display information in a grid-like format of rows \
                      and columns. They organize information in a way that's easy to \
                      scan, so that users can look for patterns and insights."
    }
    pub fn data_table_header(&self) -> &'static str {
        "Nutrition"
    }
    pub fn data_table_column_dessert(&self) -> &'static str {
        "Dessert (1 serving)"
    }
    pub fn data_table_column_calories(&self) -> &'static str {
        "Calories"
    }
    pub fn data_table_column_fat(&self) -> &'static str {
        "Fat (g)"
    }
    pub fn data_table_column_carbs(&self) -> &'static str {
        "Carbs (g)"
    }
    pub fn data_table_column_protein(&self) -> &'static str {
        "Protein (g)"
    }
    pub fn data_table_column_sodium(&self) -> &'static str {
        "Sodium (mg)"
    }
    pub fn data_table_column_calcium(&self) -> &'static str {
        "Calcium (%)"
    }
    pub fn data_table_column_iron(&self) -> &'static str {
        "Iron (%)"
    }
    pub fn data_table_row_frozen_yogurt(&self) -> &'static str {
        "Frozen yogurt"
    }
    pub fn data_table_row_ice_cream_sandwich(&self) -> &'static str {
        "Ice cream sandwich"
    }
    pub fn data_table_row_eclair(&self) -> &'static str {
        "Eclair"
    }
    pub fn data_table_row_cupcake(&self) -> &'static str {
        "Cupcake"
    }
    pub fn data_table_row_gingerbread(&self) -> &'static str {
        "Gingerbread"
    }
    pub fn data_table_row_jelly_bean(&self) -> &'static str {
        "Jelly bean"
    }
    pub fn data_table_row_lollipop(&self) -> &'static str {
        "Lollipop"
    }
    pub fn data_table_row_honeycomb(&self) -> &'static str {
        "Honeycomb"
    }
    pub fn data_table_row_donut(&self) -> &'static str {
        "Donut"
    }
    pub fn data_table_row_apple_pie(&self) -> &'static str {
        "Apple pie"
    }
    pub fn data_table_row_with_sugar(&self, value: impl std::fmt::Display) -> String {
        format!("{value} with sugar")
    }
    pub fn data_table_row_with_honey(&self, value: impl std::fmt::Display) -> String {
        format!("{value} with honey")
    }
    pub fn demo_dialog_title(&self) -> &'static str {
        "Dialogs"
    }
    pub fn demo_dialog_subtitle(&self) -> &'static str {
        "Simple, alert, and fullscreen"
    }
    pub fn demo_alert_dialog_title(&self) -> &'static str {
        "Alert"
    }
    pub fn demo_alert_dialog_description(&self) -> &'static str {
        "An alert dialog informs the user about situations that require \
                      acknowledgement. An alert dialog has an optional title and an \
                      optional list of actions."
    }
    pub fn demo_alert_title_dialog_title(&self) -> &'static str {
        "Alert With Title"
    }
    pub fn demo_simple_dialog_title(&self) -> &'static str {
        "Simple"
    }
    pub fn demo_simple_dialog_description(&self) -> &'static str {
        "A simple dialog offers the user a choice between several \
                      options. A simple dialog has an optional title that is \
                      displayed above the choices."
    }
    pub fn demo_divider_title(&self) -> &'static str {
        "Divider"
    }
    pub fn demo_divider_subtitle(&self) -> &'static str {
        "A divider is a thin line that groups content in lists and \
                      layouts."
    }
    pub fn demo_divider_description(&self) -> &'static str {
        "Dividers can be used in lists, drawers, and elsewhere to \
                      separate content."
    }
    pub fn demo_vertical_divider_title(&self) -> &'static str {
        "Vertical Divider"
    }
    pub fn demo_grid_lists_title(&self) -> &'static str {
        "Grid Lists"
    }
    pub fn demo_grid_lists_subtitle(&self) -> &'static str {
        "Row and column layout"
    }
    pub fn demo_grid_lists_description(&self) -> &'static str {
        "Grid Lists are best suited for presenting homogeneous data, \
                      typically images. Each item in a grid list is called a tile."
    }
    pub fn demo_grid_lists_image_only_title(&self) -> &'static str {
        "Image only"
    }
    pub fn demo_grid_lists_header_title(&self) -> &'static str {
        "With header"
    }
    pub fn demo_grid_lists_footer_title(&self) -> &'static str {
        "With footer"
    }
    pub fn demo_sliders_title(&self) -> &'static str {
        "Sliders"
    }
    pub fn demo_sliders_subtitle(&self) -> &'static str {
        "Widgets for selecting a value by swiping"
    }
    pub fn demo_sliders_description(&self) -> &'static str {
        "Sliders reflect a range of values along a bar, from which \
                      users may select a single value. They are ideal for adjusting \
                      settings such as volume, brightness, or applying image \
                      filters."
    }
    pub fn demo_range_sliders_title(&self) -> &'static str {
        "Range Sliders"
    }
    pub fn demo_range_sliders_description(&self) -> &'static str {
        "Sliders reflect a range of values along a bar. They can have \
                      icons on both ends of the bar that reflect a range of values. \
                      They are ideal for adjusting settings such as volume, \
                      brightness, or applying image filters."
    }
    pub fn demo_custom_sliders_title(&self) -> &'static str {
        "Custom Sliders"
    }
    pub fn demo_custom_sliders_description(&self) -> &'static str {
        "Sliders reflect a range of values along a bar, from which \
                      users may select a single value or range of values. The \
                      sliders can be themed and customized."
    }
    pub fn demo_sliders_continuous_with_editable_numerical_value(&self) -> &'static str {
        "Continuous with Editable Numerical Value"
    }
    pub fn demo_sliders_discrete(&self) -> &'static str {
        "Discrete"
    }
    pub fn demo_sliders_discrete_slider_with_custom_theme(&self) -> &'static str {
        "Discrete Slider with Custom Theme"
    }
    pub fn demo_sliders_continuous_range_slider_with_custom_theme(&self) -> &'static str {
        "Continuous Range Slider with Custom Theme"
    }
    pub fn demo_sliders_continuous(&self) -> &'static str {
        "Continuous"
    }
    pub fn demo_sliders_editable_numerical_value(&self) -> &'static str {
        "Editable numerical value"
    }
    pub fn demo_menu_title(&self) -> &'static str {
        "Menu"
    }
    pub fn demo_context_menu_title(&self) -> &'static str {
        "Context menu"
    }
    pub fn demo_sectioned_menu_title(&self) -> &'static str {
        "Sectioned menu"
    }
    pub fn demo_simple_menu_title(&self) -> &'static str {
        "Simple menu"
    }
    pub fn demo_checklist_menu_title(&self) -> &'static str {
        "Checklist menu"
    }
    pub fn demo_menu_subtitle(&self) -> &'static str {
        "Menu buttons and simple menus"
    }
    pub fn demo_menu_description(&self) -> &'static str {
        "A menu displays a list of choices on a temporary surface. They \
                      appear when users interact with a button, action, or other \
                      control."
    }
    pub fn demo_menu_item_value_one(&self) -> &'static str {
        "Menu item one"
    }
    pub fn demo_menu_item_value_two(&self) -> &'static str {
        "Menu item two"
    }
    pub fn demo_menu_item_value_three(&self) -> &'static str {
        "Menu item three"
    }
    pub fn demo_menu_one(&self) -> &'static str {
        "One"
    }
    pub fn demo_menu_two(&self) -> &'static str {
        "Two"
    }
    pub fn demo_menu_three(&self) -> &'static str {
        "Three"
    }
    pub fn demo_menu_four(&self) -> &'static str {
        "Four"
    }
    pub fn demo_menu_an_item_with_a_context_menu_button(&self) -> &'static str {
        "An item with a context menu"
    }
    pub fn demo_menu_context_menu_item_one(&self) -> &'static str {
        "Context menu item one"
    }
    pub fn demo_menu_a_disabled_menu_item(&self) -> &'static str {
        "Disabled menu item"
    }
    pub fn demo_menu_context_menu_item_three(&self) -> &'static str {
        "Context menu item three"
    }
    pub fn demo_menu_an_item_with_a_sectioned_menu(&self) -> &'static str {
        "An item with a sectioned menu"
    }
    pub fn demo_menu_preview(&self) -> &'static str {
        "Preview"
    }
    pub fn demo_menu_share(&self) -> &'static str {
        "Share"
    }
    pub fn demo_menu_get_link(&self) -> &'static str {
        "Get link"
    }
    pub fn demo_menu_remove(&self) -> &'static str {
        "Remove"
    }
    pub fn demo_menu_selected(&self, value: impl std::fmt::Display) -> String {
        format!("Selected: {value}")
    }
    pub fn demo_menu_checked(&self, value: impl std::fmt::Display) -> String {
        format!("Checked: {value}")
    }
    pub fn demo_navigation_drawer_title(&self) -> &'static str {
        "Navigation Drawer"
    }
    pub fn demo_navigation_drawer_subtitle(&self) -> &'static str {
        "Displaying a drawer within appbar"
    }
    pub fn demo_navigation_drawer_description(&self) -> &'static str {
        "A Material Design panel that slides in horizontally from the \
                      edge of the screen to show navigation links in an application."
    }
    pub fn demo_navigation_drawer_user_name(&self) -> &'static str {
        "User Name"
    }
    pub fn demo_navigation_drawer_user_email(&self) -> &'static str {
        "user.name@example.com"
    }
    pub fn demo_navigation_drawer_to_page_one(&self) -> &'static str {
        "Item One"
    }
    pub fn demo_navigation_drawer_to_page_two(&self) -> &'static str {
        "Item Two"
    }
    pub fn demo_navigation_drawer_text(&self) -> &'static str {
        "Swipe from the edge or tap the upper-left icon to see the \
                      drawer"
    }
    pub fn demo_navigation_rail_title(&self) -> &'static str {
        "Navigation Rail"
    }
    pub fn demo_navigation_rail_subtitle(&self) -> &'static str {
        "Displaying a Navigation Rail within an app"
    }
    pub fn demo_navigation_rail_description(&self) -> &'static str {
        "A material widget that is meant to be displayed at the left or \
                      right of an app to navigate between a small number of views, \
                      typically between three and five."
    }
    pub fn demo_navigation_rail_first(&self) -> &'static str {
        "First"
    }
    pub fn demo_navigation_rail_second(&self) -> &'static str {
        "Second"
    }
    pub fn demo_navigation_rail_third(&self) -> &'static str {
        "Third"
    }
    pub fn demo_menu_an_item_with_a_simple_menu(&self) -> &'static str {
        "An item with a simple menu"
    }
    pub fn demo_menu_an_item_with_a_checklist_menu(&self) -> &'static str {
        "An item with a checklist menu"
    }
    pub fn demo_fullscreen_dialog_title(&self) -> &'static str {
        "Fullscreen"
    }
    pub fn demo_fullscreen_dialog_description(&self) -> &'static str {
        "The fullscreenDialog property specifies whether the incoming \
                      page is a fullscreen modal dialog"
    }
    pub fn demo_cupertino_activity_indicator_title(&self) -> &'static str {
        "Activity indicator"
    }
    pub fn demo_cupertino_activity_indicator_subtitle(&self) -> &'static str {
        "iOS-style activity indicators"
    }
    pub fn demo_cupertino_activity_indicator_description(&self) -> &'static str {
        "An iOS-style activity indicator that spins clockwise."
    }
    pub fn demo_cupertino_buttons_title(&self) -> &'static str {
        "Buttons"
    }
    pub fn demo_cupertino_buttons_subtitle(&self) -> &'static str {
        "iOS-style buttons"
    }
    pub fn demo_cupertino_buttons_description(&self) -> &'static str {
        "An iOS-style button. It takes in text and/or an icon that \
                      fades out and in on touch. May optionally have a background."
    }
    pub fn demo_cupertino_context_menu_title(&self) -> &'static str {
        "Context Menu"
    }
    pub fn demo_cupertino_context_menu_subtitle(&self) -> &'static str {
        "iOS-style context menu"
    }
    pub fn demo_cupertino_context_menu_description(&self) -> &'static str {
        "An iOS-style full screen contextual menu that appears when an \
                      element is long-pressed."
    }
    pub fn demo_cupertino_context_menu_action_one(&self) -> &'static str {
        "Action one"
    }
    pub fn demo_cupertino_context_menu_action_two(&self) -> &'static str {
        "Action two"
    }
    pub fn demo_cupertino_context_menu_action_text(&self) -> &'static str {
        "Tap and hold the Flutter logo to see the context menu."
    }
    pub fn demo_cupertino_alerts_title(&self) -> &'static str {
        "Alerts"
    }
    pub fn demo_cupertino_alerts_subtitle(&self) -> &'static str {
        "iOS-style alert dialogs"
    }
    pub fn demo_cupertino_alert_title(&self) -> &'static str {
        "Alert"
    }
    pub fn demo_cupertino_alert_description(&self) -> &'static str {
        "An alert dialog informs the user about situations that require \
                      acknowledgement. An alert dialog has an optional title, \
                      optional content, and an optional list of actions. The title \
                      is displayed above the content and the actions are displayed \
                      below the content."
    }
    pub fn demo_cupertino_alert_with_title_title(&self) -> &'static str {
        "Alert With Title"
    }
    pub fn demo_cupertino_alert_buttons_title(&self) -> &'static str {
        "Alert With Buttons"
    }
    pub fn demo_cupertino_alert_buttons_only_title(&self) -> &'static str {
        "Alert Buttons Only"
    }
    pub fn demo_cupertino_action_sheet_title(&self) -> &'static str {
        "Action Sheet"
    }
    pub fn demo_cupertino_action_sheet_description(&self) -> &'static str {
        "An action sheet is a specific style of alert that presents the \
                      user with a set of two or more choices related to the current \
                      context. An action sheet can have a title, an additional \
                      message, and a list of actions."
    }
    pub fn demo_cupertino_navigation_bar_title(&self) -> &'static str {
        "Navigation bar"
    }
    pub fn demo_cupertino_navigation_bar_subtitle(&self) -> &'static str {
        "iOS-style navigation bar"
    }
    pub fn demo_cupertino_navigation_bar_description(&self) -> &'static str {
        "An iOS-styled navigation bar. The navigation bar is a toolbar \
                      that minimally consists of a page title, in the middle of the \
                      toolbar."
    }
    pub fn demo_cupertino_picker_title(&self) -> &'static str {
        "Pickers"
    }
    pub fn demo_cupertino_picker_subtitle(&self) -> &'static str {
        "iOS-style pickers"
    }
    pub fn demo_cupertino_picker_description(&self) -> &'static str {
        "An iOS-style picker widget that can be used to select strings, \
                      dates, times, or both date and time."
    }
    pub fn demo_cupertino_picker_timer(&self) -> &'static str {
        "Timer"
    }
    pub fn demo_cupertino_picker(&self) -> &'static str {
        "Picker"
    }
    pub fn demo_cupertino_picker_date(&self) -> &'static str {
        "Date"
    }
    pub fn demo_cupertino_picker_time(&self) -> &'static str {
        "Time"
    }
    pub fn demo_cupertino_picker_date_time(&self) -> &'static str {
        "Date and Time"
    }
    pub fn demo_cupertino_pull_to_refresh_title(&self) -> &'static str {
        "Pull to refresh"
    }
    pub fn demo_cupertino_pull_to_refresh_subtitle(&self) -> &'static str {
        "iOS-style pull to refresh control"
    }
    pub fn demo_cupertino_pull_to_refresh_description(&self) -> &'static str {
        "A widget implementing the iOS-style pull to refresh content \
                      control."
    }
    pub fn demo_cupertino_segmented_control_title(&self) -> &'static str {
        "Segmented control"
    }
    pub fn demo_cupertino_segmented_control_subtitle(&self) -> &'static str {
        "iOS-style segmented control"
    }
    pub fn demo_cupertino_segmented_control_description(&self) -> &'static str {
        "Used to select between a number of mutually exclusive options. \
                      When one option in the segmented control is selected, the \
                      other options in the segmented control cease to be selected."
    }
    pub fn demo_cupertino_slider_title(&self) -> &'static str {
        "Slider"
    }
    pub fn demo_cupertino_slider_subtitle(&self) -> &'static str {
        "iOS-style slider"
    }
    pub fn demo_cupertino_slider_description(&self) -> &'static str {
        "A slider can be used to select from either a continuous or a \
                      discrete set of values."
    }
    pub fn demo_cupertino_slider_continuous(&self, value: impl std::fmt::Display) -> String {
        format!("Continuous: {value}")
    }
    pub fn demo_cupertino_slider_discrete(&self, value: impl std::fmt::Display) -> String {
        format!("Discrete: {value}")
    }
    pub fn demo_cupertino_switch_subtitle(&self) -> &'static str {
        "iOS-style switch"
    }
    pub fn demo_cupertino_switch_description(&self) -> &'static str {
        "A switch is used to toggle the on/off state of a single \
                      setting."
    }
    pub fn demo_cupertino_tab_bar_title(&self) -> &'static str {
        "Tab bar"
    }
    pub fn demo_cupertino_tab_bar_subtitle(&self) -> &'static str {
        "iOS-style bottom tab bar"
    }
    pub fn demo_cupertino_tab_bar_description(&self) -> &'static str {
        "An iOS-style bottom navigation tab bar. Displays multiple tabs \
                      with one tab being active, the first tab by default."
    }
    pub fn cupertino_tab_bar_home_tab(&self) -> &'static str {
        "Home"
    }
    pub fn cupertino_tab_bar_chat_tab(&self) -> &'static str {
        "Chat"
    }
    pub fn cupertino_tab_bar_profile_tab(&self) -> &'static str {
        "Profile"
    }
    pub fn demo_cupertino_text_field_title(&self) -> &'static str {
        "Text fields"
    }
    pub fn demo_cupertino_text_field_subtitle(&self) -> &'static str {
        "iOS-style text fields"
    }
    pub fn demo_cupertino_text_field_description(&self) -> &'static str {
        "A text field lets the user enter text, either with a hardware \
                      keyboard or with an onscreen keyboard."
    }
    pub fn demo_cupertino_text_field_pin(&self) -> &'static str {
        "PIN"
    }
    pub fn demo_cupertino_search_text_field_title(&self) -> &'static str {
        "Search text field"
    }
    pub fn demo_cupertino_search_text_field_subtitle(&self) -> &'static str {
        "iOS-style search text field"
    }
    pub fn demo_cupertino_search_text_field_description(&self) -> &'static str {
        "A search text field that lets the user search by entering \
                      text, and that can offer and filter suggestions."
    }
    pub fn demo_cupertino_search_text_field_placeholder(&self) -> &'static str {
        "Enter some text"
    }
    pub fn demo_cupertino_scrollbar_title(&self) -> &'static str {
        "Scrollbar"
    }
    pub fn demo_cupertino_scrollbar_subtitle(&self) -> &'static str {
        "iOS-style scrollbar"
    }
    pub fn demo_cupertino_scrollbar_description(&self) -> &'static str {
        "A scrollbar that wraps the given child"
    }
    pub fn demo_motion_title(&self) -> &'static str {
        "Motion"
    }
    pub fn demo_motion_subtitle(&self) -> &'static str {
        "All of the predefined transition patterns"
    }
    pub fn demo_container_transform_demo_instructions(&self) -> &'static str {
        "Cards, Lists & FAB"
    }
    pub fn demo_shared_x_axis_demo_instructions(&self) -> &'static str {
        "Next and Back Buttons"
    }
    pub fn demo_shared_y_axis_demo_instructions(&self) -> &'static str {
        "Sort by \"Recently Played\""
    }
    pub fn demo_shared_z_axis_demo_instructions(&self) -> &'static str {
        "Settings icon button"
    }
    pub fn demo_fade_through_demo_instructions(&self) -> &'static str {
        "Bottom navigation"
    }
    pub fn demo_fade_scale_demo_instructions(&self) -> &'static str {
        "Modal and FAB"
    }
    pub fn demo_container_transform_title(&self) -> &'static str {
        "Container Transform"
    }
    pub fn demo_container_transform_description(&self) -> &'static str {
        "The container transform pattern is designed for transitions \
                      between UI elements that include a container. This pattern \
                      creates a visible connection between two UI elements"
    }
    pub fn demo_container_transform_modal_bottom_sheet_title(&self) -> &'static str {
        "Fade mode"
    }
    pub fn demo_container_transform_type_fade(&self) -> &'static str {
        "FADE"
    }
    pub fn demo_container_transform_type_fade_through(&self) -> &'static str {
        "FADE THROUGH"
    }
    pub fn demo_motion_placeholder_title(&self) -> &'static str {
        "Title"
    }
    pub fn demo_motion_placeholder_subtitle(&self) -> &'static str {
        "Secondary text"
    }
    pub fn demo_motion_small_placeholder_subtitle(&self) -> &'static str {
        "Secondary"
    }
    pub fn demo_motion_details_page_title(&self) -> &'static str {
        "Details Page"
    }
    pub fn demo_motion_list_tile_title(&self) -> &'static str {
        "List item"
    }
    pub fn demo_shared_axis_description(&self) -> &'static str {
        "The shared axis pattern is used for transitions between the UI \
                      elements that have a spatial or navigational relationship. \
                      This pattern uses a shared transformation on the x, y, or z \
                      axis to reinforce the relationship between elements."
    }
    pub fn demo_shared_x_axis_title(&self) -> &'static str {
        "Shared x-axis"
    }
    pub fn demo_shared_x_axis_back_button_text(&self) -> &'static str {
        "BACK"
    }
    pub fn demo_shared_x_axis_next_button_text(&self) -> &'static str {
        "NEXT"
    }
    pub fn demo_shared_x_axis_course_page_title(&self) -> &'static str {
        "Streamline your courses"
    }
    pub fn demo_shared_x_axis_course_page_subtitle(&self) -> &'static str {
        "Bundled categories appear as groups in your feed. You can \
                      always change this later."
    }
    pub fn demo_shared_x_axis_arts_and_crafts_course_title(&self) -> &'static str {
        "Arts & Crafts"
    }
    pub fn demo_shared_x_axis_business_course_title(&self) -> &'static str {
        "Business"
    }
    pub fn demo_shared_x_axis_illustration_course_title(&self) -> &'static str {
        "Illustration"
    }
    pub fn demo_shared_x_axis_design_course_title(&self) -> &'static str {
        "Design"
    }
    pub fn demo_shared_x_axis_culinary_course_title(&self) -> &'static str {
        "Culinary"
    }
    pub fn demo_shared_x_axis_bundled_course_subtitle(&self) -> &'static str {
        "Bundled"
    }
    pub fn demo_shared_x_axis_individual_course_subtitle(&self) -> &'static str {
        "Shown Individually"
    }
    pub fn demo_shared_x_axis_sign_in_welcome_text(&self) -> &'static str {
        "Hi David Park"
    }
    pub fn demo_shared_x_axis_sign_in_subtitle_text(&self) -> &'static str {
        "Sign in with your account"
    }
    pub fn demo_shared_x_axis_sign_in_text_field_label(&self) -> &'static str {
        "Email or phone number"
    }
    pub fn demo_shared_x_axis_forgot_email_button_text(&self) -> &'static str {
        "FORGOT EMAIL?"
    }
    pub fn demo_shared_x_axis_create_account_button_text(&self) -> &'static str {
        "CREATE ACCOUNT"
    }
    pub fn demo_shared_y_axis_title(&self) -> &'static str {
        "Shared y-axis"
    }
    pub fn demo_shared_y_axis_album_count(&self) -> &'static str {
        "268 albums"
    }
    pub fn demo_shared_y_axis_alphabetical_sort_title(&self) -> &'static str {
        "A-Z"
    }
    pub fn demo_shared_y_axis_recent_sort_title(&self) -> &'static str {
        "Recently played"
    }
    pub fn demo_shared_y_axis_album_tile_title(&self) -> &'static str {
        "Album"
    }
    pub fn demo_shared_y_axis_album_tile_subtitle(&self) -> &'static str {
        "Artist"
    }
    pub fn demo_shared_y_axis_album_tile_duration_unit(&self) -> &'static str {
        "min"
    }
    pub fn demo_shared_z_axis_title(&self) -> &'static str {
        "Shared z-axis"
    }
    pub fn demo_shared_z_axis_settings_page_title(&self) -> &'static str {
        "Settings"
    }
    pub fn demo_shared_z_axis_burger_recipe_title(&self) -> &'static str {
        "Burger"
    }
    pub fn demo_shared_z_axis_burger_recipe_description(&self) -> &'static str {
        "Burger recipe"
    }
    pub fn demo_shared_z_axis_sandwich_recipe_title(&self) -> &'static str {
        "Sandwich"
    }
    pub fn demo_shared_z_axis_sandwich_recipe_description(&self) -> &'static str {
        "Sandwich recipe"
    }
    pub fn demo_shared_z_axis_dessert_recipe_title(&self) -> &'static str {
        "Dessert"
    }
    pub fn demo_shared_z_axis_dessert_recipe_description(&self) -> &'static str {
        "Dessert recipe"
    }
    pub fn demo_shared_z_axis_shrimp_plate_recipe_title(&self) -> &'static str {
        "Shrimp"
    }
    pub fn demo_shared_z_axis_shrimp_plate_recipe_description(&self) -> &'static str {
        "Shrimp plate recipe"
    }
    pub fn demo_shared_z_axis_crab_plate_recipe_title(&self) -> &'static str {
        "Crab"
    }
    pub fn demo_shared_z_axis_crab_plate_recipe_description(&self) -> &'static str {
        "Crab plate recipe"
    }
    pub fn demo_shared_z_axis_beef_sandwich_recipe_title(&self) -> &'static str {
        "Beef Sandwich"
    }
    pub fn demo_shared_z_axis_beef_sandwich_recipe_description(&self) -> &'static str {
        "Beef Sandwich recipe"
    }
    pub fn demo_shared_z_axis_saved_recipes_list_title(&self) -> &'static str {
        "Saved Recipes"
    }
    pub fn demo_shared_z_axis_profile_setting_label(&self) -> &'static str {
        "Profile"
    }
    pub fn demo_shared_z_axis_notification_setting_label(&self) -> &'static str {
        "Notifications"
    }
    pub fn demo_shared_z_axis_privacy_setting_label(&self) -> &'static str {
        "Privacy"
    }
    pub fn demo_shared_z_axis_help_setting_label(&self) -> &'static str {
        "Help"
    }
    pub fn demo_fade_through_title(&self) -> &'static str {
        "Fade through"
    }
    pub fn demo_fade_through_description(&self) -> &'static str {
        "The fade through pattern is used for transitions between UI \
                      elements that do not have a strong relationship to each other."
    }
    pub fn demo_fade_through_albums_destination(&self) -> &'static str {
        "Albums"
    }
    pub fn demo_fade_through_photos_destination(&self) -> &'static str {
        "Photos"
    }
    pub fn demo_fade_through_search_destination(&self) -> &'static str {
        "Search"
    }
    pub fn demo_fade_through_text_placeholder(&self) -> &'static str {
        "123 photos"
    }
    pub fn demo_fade_scale_title(&self) -> &'static str {
        "Fade"
    }
    pub fn demo_fade_scale_description(&self) -> &'static str {
        "The fade pattern is used for UI elements that enter or exit \
                      within the bounds of the screen, such as a dialog that fades \
                      in the center of the screen."
    }
    pub fn demo_fade_scale_show_alert_dialog_button(&self) -> &'static str {
        "SHOW MODAL"
    }
    pub fn demo_fade_scale_show_fab_button(&self) -> &'static str {
        "SHOW FAB"
    }
    pub fn demo_fade_scale_hide_fab_button(&self) -> &'static str {
        "HIDE FAB"
    }
    pub fn demo_fade_scale_alert_dialog_header(&self) -> &'static str {
        "Alert Dialog"
    }
    pub fn demo_fade_scale_alert_dialog_cancel_button(&self) -> &'static str {
        "CANCEL"
    }
    pub fn demo_fade_scale_alert_dialog_discard_button(&self) -> &'static str {
        "DISCARD"
    }
    pub fn demo_colors_title(&self) -> &'static str {
        "Colors"
    }
    pub fn demo_colors_subtitle(&self) -> &'static str {
        "All of the predefined colors"
    }
    pub fn demo_colors_description(&self) -> &'static str {
        "Color and color swatch constants which represent Material \
                      Design's color palette."
    }
    pub fn demo_typography_title(&self) -> &'static str {
        "Typography"
    }
    pub fn demo_typography_subtitle(&self) -> &'static str {
        "All of the predefined text styles"
    }
    pub fn demo_typography_description(&self) -> &'static str {
        "Definitions for the various typographical styles found in \
                      Material Design."
    }
    pub fn demo2d_transformations_title(&self) -> &'static str {
        "2D transformations"
    }
    pub fn demo2d_transformations_subtitle(&self) -> &'static str {
        "Pan and zoom"
    }
    pub fn demo2d_transformations_description(&self) -> &'static str {
        "Tap to edit tiles, and use gestures to move around the scene. \
                      Drag to pan and pinch with two fingers to zoom. Press the \
                      reset button to return to the starting orientation."
    }
    pub fn demo2d_transformations_reset_tooltip(&self) -> &'static str {
        "Reset transformations"
    }
    pub fn demo2d_transformations_edit_tooltip(&self) -> &'static str {
        "Edit tile"
    }
    pub fn button_text(&self) -> &'static str {
        "BUTTON"
    }
    pub fn demo_bottom_sheet_title(&self) -> &'static str {
        "Bottom sheet"
    }
    pub fn demo_bottom_sheet_subtitle(&self) -> &'static str {
        "Persistent and modal bottom sheets"
    }
    pub fn demo_bottom_sheet_persistent_title(&self) -> &'static str {
        "Persistent bottom sheet"
    }
    pub fn demo_bottom_sheet_persistent_description(&self) -> &'static str {
        "A persistent bottom sheet shows information that supplements \
                      the primary content of the app. A persistent bottom sheet \
                      remains visible even when the user interacts with other parts \
                      of the app."
    }
    pub fn demo_bottom_sheet_modal_title(&self) -> &'static str {
        "Modal bottom sheet"
    }
    pub fn demo_bottom_sheet_modal_description(&self) -> &'static str {
        "A modal bottom sheet is an alternative to a menu or a dialog \
                      and prevents the user from interacting with the rest of the \
                      app."
    }
    pub fn demo_bottom_sheet_add_label(&self) -> &'static str {
        "Add"
    }
    pub fn demo_bottom_sheet_button_text(&self) -> &'static str {
        "SHOW BOTTOM SHEET"
    }
    pub fn demo_bottom_sheet_header(&self) -> &'static str {
        "Header"
    }
    pub fn demo_bottom_sheet_item(&self, value: impl std::fmt::Display) -> String {
        format!("Item {value}")
    }
    pub fn demo_lists_title(&self) -> &'static str {
        "Lists"
    }
    pub fn demo_lists_subtitle(&self) -> &'static str {
        "Scrolling list layouts"
    }
    pub fn demo_lists_description(&self) -> &'static str {
        "A single fixed-height row that typically contains some text as \
                      well as a leading or trailing icon."
    }
    pub fn demo_one_line_lists_title(&self) -> &'static str {
        "One Line"
    }
    pub fn demo_two_line_lists_title(&self) -> &'static str {
        "Two Lines"
    }
    pub fn demo_lists_secondary(&self) -> &'static str {
        "Secondary text"
    }
    pub fn demo_progress_indicator_title(&self) -> &'static str {
        "Progress indicators"
    }
    pub fn demo_progress_indicator_subtitle(&self) -> &'static str {
        "Linear, circular, indeterminate"
    }
    pub fn demo_circular_progress_indicator_title(&self) -> &'static str {
        "Circular Progress Indicator"
    }
    pub fn demo_circular_progress_indicator_description(&self) -> &'static str {
        "A Material Design circular progress indicator, which spins to \
                      indicate that the application is busy."
    }
    pub fn demo_linear_progress_indicator_title(&self) -> &'static str {
        "Linear Progress Indicator"
    }
    pub fn demo_linear_progress_indicator_description(&self) -> &'static str {
        "A Material Design linear progress indicator, also known as a \
                      progress bar."
    }
    pub fn demo_pickers_title(&self) -> &'static str {
        "Pickers"
    }
    pub fn demo_pickers_subtitle(&self) -> &'static str {
        "Date and time selection"
    }
    pub fn demo_date_picker_title(&self) -> &'static str {
        "Date Picker"
    }
    pub fn demo_date_picker_description(&self) -> &'static str {
        "Shows a dialog containing a Material Design date picker."
    }
    pub fn demo_time_picker_title(&self) -> &'static str {
        "Time Picker"
    }
    pub fn demo_time_picker_description(&self) -> &'static str {
        "Shows a dialog containing a Material Design time picker."
    }
    pub fn demo_date_range_picker_title(&self) -> &'static str {
        "Date Range Picker"
    }
    pub fn demo_date_range_picker_description(&self) -> &'static str {
        "Shows a dialog containing a Material Design date range picker."
    }
    pub fn demo_pickers_show_picker(&self) -> &'static str {
        "SHOW PICKER"
    }
    pub fn demo_tabs_title(&self) -> &'static str {
        "Tabs"
    }
    pub fn demo_tabs_scrolling_title(&self) -> &'static str {
        "Scrolling"
    }
    pub fn demo_tabs_non_scrolling_title(&self) -> &'static str {
        "Non-scrolling"
    }
    pub fn demo_tabs_subtitle(&self) -> &'static str {
        "Tabs with independently scrollable views"
    }
    pub fn demo_tabs_description(&self) -> &'static str {
        "Tabs organize content across different screens, data sets, and \
                      other interactions."
    }
    pub fn demo_snackbars_title(&self) -> &'static str {
        "Snackbars"
    }
    pub fn demo_snackbars_subtitle(&self) -> &'static str {
        "Snackbars show messages at the bottom of the screen"
    }
    pub fn demo_snackbars_description(&self) -> &'static str {
        "Snackbars inform users of a process that an app has performed \
                      or will perform. They appear temporarily, towards the bottom \
                      of the screen. They shouldn't interrupt the user experience, \
                      and they don't require user input to disappear."
    }
    pub fn demo_snackbars_button_label(&self) -> &'static str {
        "SHOW A SNACKBAR"
    }
    pub fn demo_snackbars_text(&self) -> &'static str {
        "This is a snackbar."
    }
    pub fn demo_snackbars_action_button_label(&self) -> &'static str {
        "ACTION"
    }
    pub fn demo_snackbars_action(&self) -> &'static str {
        "You pressed the snackbar action."
    }
    pub fn demo_selection_controls_title(&self) -> &'static str {
        "Selection controls"
    }
    pub fn demo_selection_controls_subtitle(&self) -> &'static str {
        "Checkboxes, radio buttons, and switches"
    }
    pub fn demo_selection_controls_checkbox_title(&self) -> &'static str {
        "Checkbox"
    }
    pub fn demo_selection_controls_checkbox_description(&self) -> &'static str {
        "Checkboxes allow the user to select multiple options from a \
                      set. A normal checkbox's value is true or false and a tristate \
                      checkbox's value can also be null."
    }
    pub fn demo_selection_controls_radio_title(&self) -> &'static str {
        "Radio"
    }
    pub fn demo_selection_controls_radio_description(&self) -> &'static str {
        "Radio buttons allow the user to select one option from a set. \
                      Use radio buttons for exclusive selection if you think that \
                      the user needs to see all available options side-by-side."
    }
    pub fn demo_selection_controls_switch_title(&self) -> &'static str {
        "Switch"
    }
    pub fn demo_selection_controls_switch_description(&self) -> &'static str {
        "On/off switches toggle the state of a single settings option. \
                      The option that the switch controls, as well as the state it's \
                      in, should be made clear from the corresponding inline label."
    }
    pub fn demo_bottom_text_fields_title(&self) -> &'static str {
        "Text fields"
    }
    pub fn demo_text_field_title(&self) -> &'static str {
        "Text fields"
    }
    pub fn demo_text_field_subtitle(&self) -> &'static str {
        "Single line of editable text and numbers"
    }
    pub fn demo_text_field_description(&self) -> &'static str {
        "Text fields allow users to enter text into a UI. They \
                      typically appear in forms and dialogs."
    }
    pub fn demo_text_field_show_password_label(&self) -> &'static str {
        "Show password"
    }
    pub fn demo_text_field_hide_password_label(&self) -> &'static str {
        "Hide password"
    }
    pub fn demo_text_field_form_errors(&self) -> &'static str {
        "Please fix the errors in red before submitting."
    }
    pub fn demo_text_field_name_required(&self) -> &'static str {
        "Name is required."
    }
    pub fn demo_text_field_only_alphabetical_chars(&self) -> &'static str {
        "Please enter only alphabetical characters."
    }
    pub fn demo_text_field_enter_us_phone_number(&self) -> &'static str {
        "(###) ###-#### - Enter a US phone number."
    }
    pub fn demo_text_field_enter_password(&self) -> &'static str {
        "Please enter a password."
    }
    pub fn demo_text_field_passwords_do_not_match(&self) -> &'static str {
        "The passwords don't match"
    }
    pub fn demo_text_field_what_do_people_call_you(&self) -> &'static str {
        "What do people call you?"
    }
    pub fn demo_text_field_name_field(&self) -> &'static str {
        "Name*"
    }
    pub fn demo_text_field_where_can_we_reach_you(&self) -> &'static str {
        "Where can we reach you?"
    }
    pub fn demo_text_field_phone_number(&self) -> &'static str {
        "Phone number*"
    }
    pub fn demo_text_field_your_email_address(&self) -> &'static str {
        "Your email address"
    }
    pub fn demo_text_field_email(&self) -> &'static str {
        "Email"
    }
    pub fn demo_text_field_tell_us_about_yourself(&self) -> &'static str {
        "Tell us about yourself (e.g., write down what you do or what \
                      hobbies you have)"
    }
    pub fn demo_text_field_keep_it_short(&self) -> &'static str {
        "Keep it short, this is just a demo."
    }
    pub fn demo_text_field_life_story(&self) -> &'static str {
        "Life story"
    }
    pub fn demo_text_field_salary(&self) -> &'static str {
        "Salary"
    }
    pub fn demo_text_field_usd(&self) -> &'static str {
        "USD"
    }
    pub fn demo_text_field_no_more_than(&self) -> &'static str {
        "No more than 8 characters."
    }
    pub fn demo_text_field_password(&self) -> &'static str {
        "Password*"
    }
    pub fn demo_text_field_retype_password(&self) -> &'static str {
        "Re-type password*"
    }
    pub fn demo_text_field_submit(&self) -> &'static str {
        "SUBMIT"
    }
    pub fn demo_text_field_name_has_phone_number(
        &self,
        name: impl std::fmt::Display,
        phone_number: impl std::fmt::Display,
    ) -> String {
        format!("{name} phone number is {phone_number}")
    }
    pub fn demo_text_field_required_field(&self) -> &'static str {
        "* indicates required field"
    }
    pub fn demo_tooltip_title(&self) -> &'static str {
        "Tooltips"
    }
    pub fn demo_tooltip_subtitle(&self) -> &'static str {
        "Short message displayed on long press or hover"
    }
    pub fn demo_tooltip_description(&self) -> &'static str {
        "Tooltips provide text labels that help explain the function of \
                      a button or other user interface action. Tooltips display \
                      informative text when users hover over, focus on, or long \
                      press an element."
    }
    pub fn demo_tooltip_instructions(&self) -> &'static str {
        "Long press or hover to display the tooltip."
    }
    pub fn bottom_navigation_comments_tab(&self) -> &'static str {
        "Comments"
    }
    pub fn bottom_navigation_calendar_tab(&self) -> &'static str {
        "Calendar"
    }
    pub fn bottom_navigation_account_tab(&self) -> &'static str {
        "Account"
    }
    pub fn bottom_navigation_alarm_tab(&self) -> &'static str {
        "Alarm"
    }
    pub fn bottom_navigation_camera_tab(&self) -> &'static str {
        "Camera"
    }
    pub fn bottom_navigation_content_placeholder(&self, title: impl std::fmt::Display) -> String {
        format!("Placeholder for {title} tab")
    }
    pub fn button_text_create(&self) -> &'static str {
        "Create"
    }
    pub fn dialog_selected_option(&self, value: impl std::fmt::Display) -> String {
        format!("You selected: \"{value}\"")
    }
    pub fn chip_turn_on_lights(&self) -> &'static str {
        "Turn on lights"
    }
    pub fn chip_small(&self) -> &'static str {
        "Small"
    }
    pub fn chip_medium(&self) -> &'static str {
        "Medium"
    }
    pub fn chip_large(&self) -> &'static str {
        "Large"
    }
    pub fn chip_elevator(&self) -> &'static str {
        "Elevator"
    }
    pub fn chip_washer(&self) -> &'static str {
        "Washer"
    }
    pub fn chip_fireplace(&self) -> &'static str {
        "Fireplace"
    }
    pub fn chip_biking(&self) -> &'static str {
        "Biking"
    }
    pub fn demo(&self) -> &'static str {
        "Demo"
    }
    pub fn bottom_app_bar(&self) -> &'static str {
        "Bottom app bar"
    }
    pub fn loading(&self) -> &'static str {
        "Loading"
    }
    pub fn dialog_discard_title(&self) -> &'static str {
        "Discard draft?"
    }
    pub fn dialog_location_title(&self) -> &'static str {
        "Use Google's location service?"
    }
    pub fn dialog_location_description(&self) -> &'static str {
        "Let Google help apps determine location. This means sending \
                      anonymous location data to Google, even when no apps are \
                      running."
    }
    pub fn dialog_cancel(&self) -> &'static str {
        "CANCEL"
    }
    pub fn dialog_discard(&self) -> &'static str {
        "DISCARD"
    }
    pub fn dialog_disagree(&self) -> &'static str {
        "DISAGREE"
    }
    pub fn dialog_agree(&self) -> &'static str {
        "AGREE"
    }
    pub fn dialog_set_backup(&self) -> &'static str {
        "Set backup account"
    }
    pub fn dialog_add_account(&self) -> &'static str {
        "Add account"
    }
    pub fn dialog_show(&self) -> &'static str {
        "SHOW DIALOG"
    }
    pub fn dialog_fullscreen_title(&self) -> &'static str {
        "Full Screen Dialog"
    }
    pub fn dialog_fullscreen_save(&self) -> &'static str {
        "SAVE"
    }
    pub fn dialog_fullscreen_description(&self) -> &'static str {
        "A full screen dialog demo"
    }
    pub fn cupertino_button(&self) -> &'static str {
        "Button"
    }
    pub fn cupertino_button_with_background(&self) -> &'static str {
        "With Background"
    }
    pub fn cupertino_alert_cancel(&self) -> &'static str {
        "Cancel"
    }
    pub fn cupertino_alert_discard(&self) -> &'static str {
        "Discard"
    }
    pub fn cupertino_alert_location_title(&self) -> &'static str {
        "Allow \"Maps\" to access your location while you are using the \
                      app?"
    }
    pub fn cupertino_alert_location_description(&self) -> &'static str {
        "Your current location will be displayed on the map and used \
                      for directions, nearby search results, and estimated travel \
                      times."
    }
    pub fn cupertino_alert_allow(&self) -> &'static str {
        "Allow"
    }
    pub fn cupertino_alert_dont_allow(&self) -> &'static str {
        "Don't Allow"
    }
    pub fn cupertino_alert_favorite_dessert(&self) -> &'static str {
        "Select Favorite Dessert"
    }
    pub fn cupertino_alert_dessert_description(&self) -> &'static str {
        "Please select your favorite type of dessert from the list \
                      below. Your selection will be used to customize the suggested \
                      list of eateries in your area."
    }
    pub fn cupertino_alert_cheesecake(&self) -> &'static str {
        "Cheesecake"
    }
    pub fn cupertino_alert_tiramisu(&self) -> &'static str {
        "Tiramisu"
    }
    pub fn cupertino_alert_apple_pie(&self) -> &'static str {
        "Apple Pie"
    }
    pub fn cupertino_alert_chocolate_brownie(&self) -> &'static str {
        "Chocolate Brownie"
    }
    pub fn cupertino_show_alert(&self) -> &'static str {
        "Show Alert"
    }
    pub fn colors_red(&self) -> &'static str {
        "RED"
    }
    pub fn colors_pink(&self) -> &'static str {
        "PINK"
    }
    pub fn colors_purple(&self) -> &'static str {
        "PURPLE"
    }
    pub fn colors_deep_purple(&self) -> &'static str {
        "DEEP PURPLE"
    }
    pub fn colors_indigo(&self) -> &'static str {
        "INDIGO"
    }
    pub fn colors_blue(&self) -> &'static str {
        "BLUE"
    }
    pub fn colors_light_blue(&self) -> &'static str {
        "LIGHT BLUE"
    }
    pub fn colors_cyan(&self) -> &'static str {
        "CYAN"
    }
    pub fn colors_teal(&self) -> &'static str {
        "TEAL"
    }
    pub fn colors_green(&self) -> &'static str {
        "GREEN"
    }
    pub fn colors_light_green(&self) -> &'static str {
        "LIGHT GREEN"
    }
    pub fn colors_lime(&self) -> &'static str {
        "LIME"
    }
    pub fn colors_yellow(&self) -> &'static str {
        "YELLOW"
    }
    pub fn colors_amber(&self) -> &'static str {
        "AMBER"
    }
    pub fn colors_orange(&self) -> &'static str {
        "ORANGE"
    }
    pub fn colors_deep_orange(&self) -> &'static str {
        "DEEP ORANGE"
    }
    pub fn colors_brown(&self) -> &'static str {
        "BROWN"
    }
    pub fn colors_grey(&self) -> &'static str {
        "GREY"
    }
    pub fn colors_blue_grey(&self) -> &'static str {
        "BLUE GREY"
    }
    pub fn place_chennai(&self) -> &'static str {
        "Chennai"
    }
    pub fn place_tanjore(&self) -> &'static str {
        "Tanjore"
    }
    pub fn place_chettinad(&self) -> &'static str {
        "Chettinad"
    }
    pub fn place_pondicherry(&self) -> &'static str {
        "Pondicherry"
    }
    pub fn place_flower_market(&self) -> &'static str {
        "Flower Market"
    }
    pub fn place_bronze_works(&self) -> &'static str {
        "Bronze Works"
    }
    pub fn place_market(&self) -> &'static str {
        "Market"
    }
    pub fn place_thanjavur_temple(&self) -> &'static str {
        "Thanjavur Temple"
    }
    pub fn place_salt_farm(&self) -> &'static str {
        "Salt Farm"
    }
    pub fn place_scooters(&self) -> &'static str {
        "Scooters"
    }
    pub fn place_silk_maker(&self) -> &'static str {
        "Silk Maker"
    }
    pub fn place_lunch_prep(&self) -> &'static str {
        "Lunch Prep"
    }
    pub fn place_beach(&self) -> &'static str {
        "Beach"
    }
    pub fn place_fisherman(&self) -> &'static str {
        "Fisherman"
    }
    pub fn starter_app_title(&self) -> &'static str {
        "Starter app"
    }
    pub fn starter_app_description(&self) -> &'static str {
        "A responsive starter layout"
    }
    pub fn starter_app_generic_button(&self) -> &'static str {
        "BUTTON"
    }
    pub fn starter_app_tooltip_add(&self) -> &'static str {
        "Add"
    }
    pub fn starter_app_tooltip_favorite(&self) -> &'static str {
        "Favorite"
    }
    pub fn starter_app_tooltip_share(&self) -> &'static str {
        "Share"
    }
    pub fn starter_app_tooltip_search(&self) -> &'static str {
        "Search"
    }
    pub fn starter_app_generic_title(&self) -> &'static str {
        "Title"
    }
    pub fn starter_app_generic_subtitle(&self) -> &'static str {
        "Subtitle"
    }
    pub fn starter_app_generic_headline(&self) -> &'static str {
        "Headline"
    }
    pub fn starter_app_generic_body(&self) -> &'static str {
        "Body"
    }
    pub fn starter_app_drawer_item(&self, value: impl std::fmt::Display) -> String {
        format!("Item {value}")
    }
    pub fn shrine_menu_caption(&self) -> &'static str {
        "MENU"
    }
    pub fn shrine_category_name_all(&self) -> &'static str {
        "ALL"
    }
    pub fn shrine_category_name_accessories(&self) -> &'static str {
        "ACCESSORIES"
    }
    pub fn shrine_category_name_clothing(&self) -> &'static str {
        "CLOTHING"
    }
    pub fn shrine_category_name_home(&self) -> &'static str {
        "HOME"
    }
    pub fn shrine_logout_button_caption(&self) -> &'static str {
        "LOGOUT"
    }
    pub fn shrine_login_username_label(&self) -> &'static str {
        "Username"
    }
    pub fn shrine_login_password_label(&self) -> &'static str {
        "Password"
    }
    pub fn shrine_cancel_button_caption(&self) -> &'static str {
        "CANCEL"
    }
    pub fn shrine_next_button_caption(&self) -> &'static str {
        "NEXT"
    }
    pub fn shrine_cart_page_caption(&self) -> &'static str {
        "CART"
    }
    pub fn shrine_product_quantity(&self, quantity: impl std::fmt::Display) -> String {
        format!("Quantity: {quantity}")
    }
    pub fn shrine_product_price(&self, price: impl std::fmt::Display) -> String {
        format!("x {price}")
    }
    pub fn shrine_cart_item_count(&self, quantity: i64) -> String {
        // intl's English plural rules select `one` at exactly 1 and
        // `other` otherwise, so the zero form upstream declares
        // ('NO ITEMS') never renders in English.
        if quantity == 1 {
            "1 ITEM".to_string()
        } else {
            format!("{quantity} ITEMS")
        }
    }
    pub fn shrine_cart_clear_button_caption(&self) -> &'static str {
        "CLEAR CART"
    }
    pub fn shrine_cart_total_caption(&self) -> &'static str {
        "TOTAL"
    }
    pub fn shrine_cart_subtotal_caption(&self) -> &'static str {
        "Subtotal:"
    }
    pub fn shrine_cart_shipping_caption(&self) -> &'static str {
        "Shipping:"
    }
    pub fn shrine_cart_tax_caption(&self) -> &'static str {
        "Tax:"
    }
    pub fn shrine_product_vagabond_sack(&self) -> &'static str {
        "Vagabond sack"
    }
    pub fn shrine_product_stella_sunglasses(&self) -> &'static str {
        "Stella sunglasses"
    }
    pub fn shrine_product_whitney_belt(&self) -> &'static str {
        "Whitney belt"
    }
    pub fn shrine_product_garden_strand(&self) -> &'static str {
        "Garden strand"
    }
    pub fn shrine_product_strut_earrings(&self) -> &'static str {
        "Strut earrings"
    }
    pub fn shrine_product_varsity_socks(&self) -> &'static str {
        "Varsity socks"
    }
    pub fn shrine_product_weave_keyring(&self) -> &'static str {
        "Weave keyring"
    }
    pub fn shrine_product_gatsby_hat(&self) -> &'static str {
        "Gatsby hat"
    }
    pub fn shrine_product_shrug_bag(&self) -> &'static str {
        "Shrug bag"
    }
    pub fn shrine_product_gilt_desk_trio(&self) -> &'static str {
        "Gilt desk trio"
    }
    pub fn shrine_product_copper_wire_rack(&self) -> &'static str {
        "Copper wire rack"
    }
    pub fn shrine_product_soothe_ceramic_set(&self) -> &'static str {
        "Soothe ceramic set"
    }
    pub fn shrine_product_hurrahs_tea_set(&self) -> &'static str {
        "Hurrahs tea set"
    }
    pub fn shrine_product_blue_stone_mug(&self) -> &'static str {
        "Blue stone mug"
    }
    pub fn shrine_product_rainwater_tray(&self) -> &'static str {
        "Rainwater tray"
    }
    pub fn shrine_product_chambray_napkins(&self) -> &'static str {
        "Chambray napkins"
    }
    pub fn shrine_product_succulent_planters(&self) -> &'static str {
        "Succulent planters"
    }
    pub fn shrine_product_quartet_table(&self) -> &'static str {
        "Quartet table"
    }
    pub fn shrine_product_kitchen_quattro(&self) -> &'static str {
        "Kitchen quattro"
    }
    pub fn shrine_product_clay_sweater(&self) -> &'static str {
        "Clay sweater"
    }
    pub fn shrine_product_sea_tunic(&self) -> &'static str {
        "Sea tunic"
    }
    pub fn shrine_product_plaster_tunic(&self) -> &'static str {
        "Plaster tunic"
    }
    pub fn shrine_product_white_pinstripe_shirt(&self) -> &'static str {
        "White pinstripe shirt"
    }
    pub fn shrine_product_chambray_shirt(&self) -> &'static str {
        "Chambray shirt"
    }
    pub fn shrine_product_seabreeze_sweater(&self) -> &'static str {
        "Seabreeze sweater"
    }
    pub fn shrine_product_gentry_jacket(&self) -> &'static str {
        "Gentry jacket"
    }
    pub fn shrine_product_navy_trousers(&self) -> &'static str {
        "Navy trousers"
    }
    pub fn shrine_product_walter_henley_white(&self) -> &'static str {
        "Walter henley (white)"
    }
    pub fn shrine_product_surf_and_perf_shirt(&self) -> &'static str {
        "Surf and perf shirt"
    }
    pub fn shrine_product_ginger_scarf(&self) -> &'static str {
        "Ginger scarf"
    }
    pub fn shrine_product_ramona_crossover(&self) -> &'static str {
        "Ramona crossover"
    }
    pub fn shrine_product_classic_white_collar(&self) -> &'static str {
        "Classic white collar"
    }
    pub fn shrine_product_cerise_scallop_tee(&self) -> &'static str {
        "Cerise scallop tee"
    }
    pub fn shrine_product_shoulder_rolls_tee(&self) -> &'static str {
        "Shoulder rolls tee"
    }
    pub fn shrine_product_grey_slouch_tank(&self) -> &'static str {
        "Grey slouch tank"
    }
    pub fn shrine_product_sunshirt_dress(&self) -> &'static str {
        "Sunshirt dress"
    }
    pub fn shrine_product_fine_lines_tee(&self) -> &'static str {
        "Fine lines tee"
    }
    pub fn shrine_tooltip_search(&self) -> &'static str {
        "Search"
    }
    pub fn shrine_tooltip_settings(&self) -> &'static str {
        "Settings"
    }
    pub fn shrine_tooltip_open_menu(&self) -> &'static str {
        "Open menu"
    }
    pub fn shrine_tooltip_close_menu(&self) -> &'static str {
        "Close menu"
    }
    pub fn shrine_tooltip_close_cart(&self) -> &'static str {
        "Close cart"
    }
    pub fn shrine_screen_reader_cart(&self, quantity: i64) -> String {
        // intl's English plural rules select `one` at exactly 1 and
        // `other` otherwise, so the zero form upstream declares
        // ('Shopping cart, no items') never renders in English.
        if quantity == 1 {
            "Shopping cart, 1 item".to_string()
        } else {
            format!("Shopping cart, {quantity} items")
        }
    }
    pub fn shrine_screen_reader_product_add_to_cart(&self) -> &'static str {
        "Add to cart"
    }
    pub fn shrine_screen_reader_remove_product_button(
        &self,
        product: impl std::fmt::Display,
    ) -> String {
        format!("Remove {product}")
    }
    pub fn shrine_tooltip_remove_item(&self) -> &'static str {
        "Remove item"
    }
    pub fn crane_form_diners(&self) -> &'static str {
        "Diners"
    }
    pub fn crane_form_date(&self) -> &'static str {
        "Select Date"
    }
    pub fn crane_form_time(&self) -> &'static str {
        "Select Time"
    }
    pub fn crane_form_location(&self) -> &'static str {
        "Select Location"
    }
    pub fn crane_form_travelers(&self) -> &'static str {
        "Travelers"
    }
    pub fn crane_form_origin(&self) -> &'static str {
        "Choose Origin"
    }
    pub fn crane_form_destination(&self) -> &'static str {
        "Choose Destination"
    }
    pub fn crane_form_dates(&self) -> &'static str {
        "Select Dates"
    }
    pub fn crane_hours(&self, hours: i64) -> String {
        if hours == 1 {
            "1h".to_string()
        } else {
            format!("${{hours}}h")
        }
    }
    pub fn crane_minutes(&self, minutes: i64) -> String {
        if minutes == 1 {
            "1m".to_string()
        } else {
            format!("${{minutes}}m")
        }
    }
    pub fn crane_flight_duration(
        &self,
        hours_short_form: impl std::fmt::Display,
        minutes_short_form: impl std::fmt::Display,
    ) -> String {
        format!("{hours_short_form} {minutes_short_form}")
    }
    pub fn crane_fly(&self) -> &'static str {
        "FLY"
    }
    pub fn crane_sleep(&self) -> &'static str {
        "SLEEP"
    }
    pub fn crane_eat(&self) -> &'static str {
        "EAT"
    }
    pub fn crane_fly_subhead(&self) -> &'static str {
        "Explore Flights by Destination"
    }
    pub fn crane_sleep_subhead(&self) -> &'static str {
        "Explore Properties by Destination"
    }
    pub fn crane_eat_subhead(&self) -> &'static str {
        "Explore Restaurants by Destination"
    }
    pub fn crane_fly_stops(&self, number_of_stops: i64) -> String {
        // intl's English plural rules select `one` at exactly 1 and
        // `other` otherwise, so the zero form upstream declares
        // ('Nonstop') never renders in English.
        if number_of_stops == 1 {
            "1 stop".to_string()
        } else {
            format!("{number_of_stops} stops")
        }
    }
    pub fn crane_sleep_properties(&self, total_properties: i64) -> String {
        // intl's English plural rules select `one` at exactly 1 and
        // `other` otherwise, so the zero form upstream declares
        // ('No Available Properties') never renders in English.
        if total_properties == 1 {
            "1 Available Properties".to_string()
        } else {
            format!("{total_properties} Available Properties")
        }
    }
    pub fn crane_eat_restaurants(&self, total_restaurants: i64) -> String {
        // intl's English plural rules select `one` at exactly 1 and
        // `other` otherwise, so the zero form upstream declares
        // ('No Restaurants') never renders in English.
        if total_restaurants == 1 {
            "1 Restaurant".to_string()
        } else {
            format!("{total_restaurants} Restaurants")
        }
    }
    pub fn crane_fly0(&self) -> &'static str {
        "Aspen, United States"
    }
    pub fn crane_fly1(&self) -> &'static str {
        "Big Sur, United States"
    }
    pub fn crane_fly2(&self) -> &'static str {
        "Khumbu Valley, Nepal"
    }
    pub fn crane_fly3(&self) -> &'static str {
        "Machu Picchu, Peru"
    }
    pub fn crane_fly4(&self) -> &'static str {
        "Malé, Maldives"
    }
    pub fn crane_fly5(&self) -> &'static str {
        "Vitznau, Switzerland"
    }
    pub fn crane_fly6(&self) -> &'static str {
        "Mexico City, Mexico"
    }
    pub fn crane_fly7(&self) -> &'static str {
        "Mount Rushmore, United States"
    }
    pub fn crane_fly8(&self) -> &'static str {
        "Singapore"
    }
    pub fn crane_fly9(&self) -> &'static str {
        "Havana, Cuba"
    }
    pub fn crane_fly10(&self) -> &'static str {
        "Cairo, Egypt"
    }
    pub fn crane_fly11(&self) -> &'static str {
        "Lisbon, Portugal"
    }
    pub fn crane_fly12(&self) -> &'static str {
        "Napa, United States"
    }
    pub fn crane_fly13(&self) -> &'static str {
        "Bali, Indonesia"
    }
    pub fn crane_sleep0(&self) -> &'static str {
        "Malé, Maldives"
    }
    pub fn crane_sleep1(&self) -> &'static str {
        "Aspen, United States"
    }
    pub fn crane_sleep2(&self) -> &'static str {
        "Machu Picchu, Peru"
    }
    pub fn crane_sleep3(&self) -> &'static str {
        "Havana, Cuba"
    }
    pub fn crane_sleep4(&self) -> &'static str {
        "Vitznau, Switzerland"
    }
    pub fn crane_sleep5(&self) -> &'static str {
        "Big Sur, United States"
    }
    pub fn crane_sleep6(&self) -> &'static str {
        "Napa, United States"
    }
    pub fn crane_sleep7(&self) -> &'static str {
        "Porto, Portugal"
    }
    pub fn crane_sleep8(&self) -> &'static str {
        "Tulum, Mexico"
    }
    pub fn crane_sleep9(&self) -> &'static str {
        "Lisbon, Portugal"
    }
    pub fn crane_sleep10(&self) -> &'static str {
        "Cairo, Egypt"
    }
    pub fn crane_sleep11(&self) -> &'static str {
        "Taipei, Taiwan"
    }
    pub fn crane_eat0(&self) -> &'static str {
        "Naples, Italy"
    }
    pub fn crane_eat1(&self) -> &'static str {
        "Dallas, United States"
    }
    pub fn crane_eat2(&self) -> &'static str {
        "Córdoba, Argentina"
    }
    pub fn crane_eat3(&self) -> &'static str {
        "Portland, United States"
    }
    pub fn crane_eat4(&self) -> &'static str {
        "Paris, France"
    }
    pub fn crane_eat5(&self) -> &'static str {
        "Seoul, South Korea"
    }
    pub fn crane_eat6(&self) -> &'static str {
        "Seattle, United States"
    }
    pub fn crane_eat7(&self) -> &'static str {
        "Nashville, United States"
    }
    pub fn crane_eat8(&self) -> &'static str {
        "Atlanta, United States"
    }
    pub fn crane_eat9(&self) -> &'static str {
        "Madrid, Spain"
    }
    pub fn crane_eat10(&self) -> &'static str {
        "Lisbon, Portugal"
    }
    pub fn crane_fly0_semantic_label(&self) -> &'static str {
        "Chalet in a snowy landscape with evergreen trees"
    }
    pub fn crane_fly1_semantic_label(&self) -> &'static str {
        "Tent in a field"
    }
    pub fn crane_fly2_semantic_label(&self) -> &'static str {
        "Prayer flags in front of snowy mountain"
    }
    pub fn crane_fly3_semantic_label(&self) -> &'static str {
        "Machu Picchu citadel"
    }
    pub fn crane_fly4_semantic_label(&self) -> &'static str {
        "Overwater bungalows"
    }
    pub fn crane_fly5_semantic_label(&self) -> &'static str {
        "Lake-side hotel in front of mountains"
    }
    pub fn crane_fly6_semantic_label(&self) -> &'static str {
        "Aerial view of Palacio de Bellas Artes"
    }
    pub fn crane_fly7_semantic_label(&self) -> &'static str {
        "Mount Rushmore"
    }
    pub fn crane_fly8_semantic_label(&self) -> &'static str {
        "Supertree Grove"
    }
    pub fn crane_fly9_semantic_label(&self) -> &'static str {
        "Man leaning on an antique blue car"
    }
    pub fn crane_fly10_semantic_label(&self) -> &'static str {
        "Al-Azhar Mosque towers during sunset"
    }
    pub fn crane_fly11_semantic_label(&self) -> &'static str {
        "Brick lighthouse at sea"
    }
    pub fn crane_fly12_semantic_label(&self) -> &'static str {
        "Pool with palm trees"
    }
    pub fn crane_fly13_semantic_label(&self) -> &'static str {
        "Sea-side pool with palm trees"
    }
    pub fn crane_sleep0_semantic_label(&self) -> &'static str {
        "Overwater bungalows"
    }
    pub fn crane_sleep1_semantic_label(&self) -> &'static str {
        "Chalet in a snowy landscape with evergreen trees"
    }
    pub fn crane_sleep2_semantic_label(&self) -> &'static str {
        "Machu Picchu citadel"
    }
    pub fn crane_sleep3_semantic_label(&self) -> &'static str {
        "Man leaning on an antique blue car"
    }
    pub fn crane_sleep4_semantic_label(&self) -> &'static str {
        "Lake-side hotel in front of mountains"
    }
    pub fn crane_sleep5_semantic_label(&self) -> &'static str {
        "Tent in a field"
    }
    pub fn crane_sleep6_semantic_label(&self) -> &'static str {
        "Pool with palm trees"
    }
    pub fn crane_sleep7_semantic_label(&self) -> &'static str {
        "Colorful apartments at Riberia Square"
    }
    pub fn crane_sleep8_semantic_label(&self) -> &'static str {
        "Mayan ruins on a cliff above a beach"
    }
    pub fn crane_sleep9_semantic_label(&self) -> &'static str {
        "Brick lighthouse at sea"
    }
    pub fn crane_sleep10_semantic_label(&self) -> &'static str {
        "Al-Azhar Mosque towers during sunset"
    }
    pub fn crane_sleep11_semantic_label(&self) -> &'static str {
        "Taipei 101 skyscraper"
    }
    pub fn crane_eat0_semantic_label(&self) -> &'static str {
        "Pizza in a wood-fired oven"
    }
    pub fn crane_eat1_semantic_label(&self) -> &'static str {
        "Empty bar with diner-style stools"
    }
    pub fn crane_eat2_semantic_label(&self) -> &'static str {
        "Burger"
    }
    pub fn crane_eat3_semantic_label(&self) -> &'static str {
        "Korean taco"
    }
    pub fn crane_eat4_semantic_label(&self) -> &'static str {
        "Chocolate dessert"
    }
    pub fn crane_eat5_semantic_label(&self) -> &'static str {
        "Artsy restaurant seating area"
    }
    pub fn crane_eat6_semantic_label(&self) -> &'static str {
        "Shrimp dish"
    }
    pub fn crane_eat7_semantic_label(&self) -> &'static str {
        "Bakery entrance"
    }
    pub fn crane_eat8_semantic_label(&self) -> &'static str {
        "Plate of crawfish"
    }
    pub fn crane_eat9_semantic_label(&self) -> &'static str {
        "Cafe counter with pastries"
    }
    pub fn crane_eat10_semantic_label(&self) -> &'static str {
        "Woman holding huge pastrami sandwich"
    }
    pub fn fortnightly_menu_front_page(&self) -> &'static str {
        "Front Page"
    }
    pub fn fortnightly_menu_world(&self) -> &'static str {
        "World"
    }
    pub fn fortnightly_menu_us(&self) -> &'static str {
        "US"
    }
    pub fn fortnightly_menu_politics(&self) -> &'static str {
        "Politics"
    }
    pub fn fortnightly_menu_business(&self) -> &'static str {
        "Business"
    }
    pub fn fortnightly_menu_tech(&self) -> &'static str {
        "Tech"
    }
    pub fn fortnightly_menu_science(&self) -> &'static str {
        "Science"
    }
    pub fn fortnightly_menu_sports(&self) -> &'static str {
        "Sports"
    }
    pub fn fortnightly_menu_travel(&self) -> &'static str {
        "Travel"
    }
    pub fn fortnightly_menu_culture(&self) -> &'static str {
        "Culture"
    }
    pub fn fortnightly_trending_tech_design(&self) -> &'static str {
        "TechDesign"
    }
    pub fn fortnightly_trending_reform(&self) -> &'static str {
        "Reform"
    }
    pub fn fortnightly_trending_healthcare_revolution(&self) -> &'static str {
        "HealthcareRevolution"
    }
    pub fn fortnightly_trending_green_army(&self) -> &'static str {
        "GreenArmy"
    }
    pub fn fortnightly_trending_stocks(&self) -> &'static str {
        "Stocks"
    }
    pub fn fortnightly_latest_updates(&self) -> &'static str {
        "Latest Updates"
    }
    pub fn fortnightly_headline_healthcare(&self) -> &'static str {
        "The Quiet, Yet Powerful Healthcare Revolution"
    }
    pub fn fortnightly_headline_war(&self) -> &'static str {
        "Divided American Lives During War"
    }
    pub fn fortnightly_headline_gasoline(&self) -> &'static str {
        "The Future of Gasoline"
    }
    pub fn fortnightly_headline_army(&self) -> &'static str {
        "Reforming The Green Army From Within"
    }
    pub fn fortnightly_headline_stocks(&self) -> &'static str {
        "As Stocks Stagnate, Many Look To Currency"
    }
    pub fn fortnightly_headline_fabrics(&self) -> &'static str {
        "Designers Use Tech To Make Futuristic Fabrics"
    }
    pub fn fortnightly_headline_feminists(&self) -> &'static str {
        "Feminists Take On Partisanship"
    }
    pub fn fortnightly_headline_bees(&self) -> &'static str {
        "Farmland Bees In Short Supply"
    }
    pub fn reply_inbox_label(&self) -> &'static str {
        "Inbox"
    }
    pub fn reply_starred_label(&self) -> &'static str {
        "Starred"
    }
    pub fn reply_sent_label(&self) -> &'static str {
        "Sent"
    }
    pub fn reply_trash_label(&self) -> &'static str {
        "Trash"
    }
    pub fn reply_spam_label(&self) -> &'static str {
        "Spam"
    }
    pub fn reply_drafts_label(&self) -> &'static str {
        "Drafts"
    }
    pub fn demo_two_pane_foldable_label(&self) -> &'static str {
        "Foldable"
    }
    pub fn demo_two_pane_foldable_description(&self) -> &'static str {
        "This is how TwoPane behaves on a foldable device."
    }
    pub fn demo_two_pane_small_screen_label(&self) -> &'static str {
        "Small Screen"
    }
    pub fn demo_two_pane_small_screen_description(&self) -> &'static str {
        "This is how TwoPane behaves on a small screen device."
    }
    pub fn demo_two_pane_tablet_label(&self) -> &'static str {
        "Tablet / Desktop"
    }
    pub fn demo_two_pane_tablet_description(&self) -> &'static str {
        "This is how TwoPane behaves on a larger screen like a tablet \
                      or desktop."
    }
    pub fn demo_two_pane_title(&self) -> &'static str {
        "TwoPane"
    }
    pub fn demo_two_pane_subtitle(&self) -> &'static str {
        "Responsive layouts on foldable, large, and small screens"
    }
    pub fn splash_select_demo(&self) -> &'static str {
        "Select a demo"
    }
    pub fn demo_two_pane_list(&self) -> &'static str {
        "List"
    }
    pub fn demo_two_pane_details(&self) -> &'static str {
        "Details"
    }
    pub fn demo_two_pane_select_item(&self) -> &'static str {
        "Select an item"
    }
    pub fn demo_two_pane_item(&self, value: impl std::fmt::Display) -> String {
        format!("Item {value}")
    }
    pub fn demo_two_pane_item_details(&self, value: impl std::fmt::Display) -> String {
        format!("Item {value} details")
    }
}
