// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! Generated by `tools/gen_l10n.py`; do not edit by hand.
//!
//! aligned to upstream gallery_localizations_ka.dart; strings not
//! ported (English only per PORTING.md).
