// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! Shrine's catalogue, generated by `tools/gen_shrine.py`.
//!
//! Maps to upstream `lib/studies/shrine/model/products_repository.dart`
//! (flutter/gallery @ d12640d). Names, prices, categories and aspect
//! ratios come from that file; the photographs come
//! from the `shrine_images` package, keyed by product id, which is why the
//! ids are kept rather than renumbered.
//!
//! Do not edit by hand.

/// One thing for sale.
#[derive(Clone, Copy, Debug)]
pub struct Product {
    pub id: u32,
    pub name: &'static str,
    pub price: u32,
    pub category: Category,
    /// Upstream's `assetAspectRatio`: the photograph's width over its
    /// height. A tile that ignored it would letterbox or crop.
    ///
    /// Carried but not yet read -- the grid sizes its tiles uniformly. It is
    /// part of the data as upstream publishes it, and the tests check it.
    #[allow(dead_code)]
    pub ratio: f32,
    pub photo: &'static [u8],
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Category {
    Accessories,
    Home,
    Clothing,
}

impl Category {
    pub fn title(self) -> &'static str {
        match self {
            Category::Accessories => "ACCESSORIES",
            Category::Home => "HOME",
            Category::Clothing => "CLOTHING",
        }
    }
}

/// The filter row, with "all" first the way upstream has it.
pub const CATEGORIES: &[Option<Category>] = &[
    None,
    Some(Category::Accessories),
    Some(Category::Home),
    Some(Category::Clothing),
];

pub const PRODUCTS: &[Product] = &[
    Product {
        id: 0,
        name: "Vagabond sack",
        price: 120,
        category: Category::Accessories,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/0-0.jpg"),
    },
    Product {
        id: 1,
        name: "Stella sunglasses",
        price: 58,
        category: Category::Accessories,
        ratio: 1.3320,
        photo: include_bytes!("../../../../assets/shrine/1-0.jpg"),
    },
    Product {
        id: 2,
        name: "Whitney belt",
        price: 35,
        category: Category::Accessories,
        ratio: 1.4430,
        photo: include_bytes!("../../../../assets/shrine/2-0.jpg"),
    },
    Product {
        id: 3,
        name: "Garden strand",
        price: 98,
        category: Category::Accessories,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/3-0.jpg"),
    },
    Product {
        id: 4,
        name: "Strut earrings",
        price: 34,
        category: Category::Accessories,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/4-0.jpg"),
    },
    Product {
        id: 5,
        name: "Varsity socks",
        price: 12,
        category: Category::Accessories,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/5-0.jpg"),
    },
    Product {
        id: 6,
        name: "Weave keyring",
        price: 16,
        category: Category::Accessories,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/6-0.jpg"),
    },
    Product {
        id: 7,
        name: "Gatsby hat",
        price: 40,
        category: Category::Accessories,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/7-0.jpg"),
    },
    Product {
        id: 8,
        name: "Shrug bag",
        price: 198,
        category: Category::Accessories,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/8-0.jpg"),
    },
    Product {
        id: 9,
        name: "Gilt desk trio",
        price: 58,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/9-0.jpg"),
    },
    Product {
        id: 10,
        name: "Copper wire rack",
        price: 18,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/10-0.jpg"),
    },
    Product {
        id: 11,
        name: "Soothe ceramic set",
        price: 28,
        category: Category::Home,
        ratio: 1.3320,
        photo: include_bytes!("../../../../assets/shrine/11-0.jpg"),
    },
    Product {
        id: 12,
        name: "Hurrahs tea set",
        price: 34,
        category: Category::Home,
        ratio: 1.5446,
        photo: include_bytes!("../../../../assets/shrine/12-0.jpg"),
    },
    Product {
        id: 13,
        name: "Blue stone mug",
        price: 18,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/13-0.jpg"),
    },
    Product {
        id: 14,
        name: "Rainwater tray",
        price: 27,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/14-0.jpg"),
    },
    Product {
        id: 15,
        name: "Chambray napkins",
        price: 16,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/15-0.jpg"),
    },
    Product {
        id: 16,
        name: "Succulent planters",
        price: 16,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/16-0.jpg"),
    },
    Product {
        id: 17,
        name: "Quartet table",
        price: 175,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/17-0.jpg"),
    },
    Product {
        id: 18,
        name: "Kitchen quattro",
        price: 129,
        category: Category::Home,
        ratio: 1.3374,
        photo: include_bytes!("../../../../assets/shrine/18-0.jpg"),
    },
    Product {
        id: 19,
        name: "Clay sweater",
        price: 48,
        category: Category::Clothing,
        ratio: 1.5023,
        photo: include_bytes!("../../../../assets/shrine/19-0.jpg"),
    },
    Product {
        id: 20,
        name: "Sea tunic",
        price: 45,
        category: Category::Clothing,
        ratio: 1.4887,
        photo: include_bytes!("../../../../assets/shrine/20-0.jpg"),
    },
    Product {
        id: 21,
        name: "Plaster tunic",
        price: 38,
        category: Category::Clothing,
        ratio: 0.6687,
        photo: include_bytes!("../../../../assets/shrine/21-0.jpg"),
    },
    Product {
        id: 22,
        name: "White pinstripe shirt",
        price: 70,
        category: Category::Clothing,
        ratio: 0.6657,
        photo: include_bytes!("../../../../assets/shrine/22-0.jpg"),
    },
    Product {
        id: 23,
        name: "Chambray shirt",
        price: 70,
        category: Category::Clothing,
        ratio: 1.4887,
        photo: include_bytes!("../../../../assets/shrine/23-0.jpg"),
    },
    Product {
        id: 24,
        name: "Seabreeze sweater",
        price: 60,
        category: Category::Clothing,
        ratio: 0.6687,
        photo: include_bytes!("../../../../assets/shrine/24-0.jpg"),
    },
    Product {
        id: 25,
        name: "Gentry jacket",
        price: 178,
        category: Category::Clothing,
        ratio: 1.5023,
        photo: include_bytes!("../../../../assets/shrine/25-0.jpg"),
    },
    Product {
        id: 26,
        name: "Navy trousers",
        price: 74,
        category: Category::Clothing,
        ratio: 0.6687,
        photo: include_bytes!("../../../../assets/shrine/26-0.jpg"),
    },
    Product {
        id: 27,
        name: "Walter henley (white)",
        price: 38,
        category: Category::Clothing,
        ratio: 0.6657,
        photo: include_bytes!("../../../../assets/shrine/27-0.jpg"),
    },
    Product {
        id: 28,
        name: "Surf and perf shirt",
        price: 48,
        category: Category::Clothing,
        ratio: 1.5023,
        photo: include_bytes!("../../../../assets/shrine/28-0.jpg"),
    },
    Product {
        id: 29,
        name: "Ginger scarf",
        price: 98,
        category: Category::Clothing,
        ratio: 0.6657,
        photo: include_bytes!("../../../../assets/shrine/29-0.jpg"),
    },
    Product {
        id: 30,
        name: "Ramona crossover",
        price: 68,
        category: Category::Clothing,
        ratio: 0.6687,
        photo: include_bytes!("../../../../assets/shrine/30-0.jpg"),
    },
    Product {
        id: 31,
        name: "Chambray shirt",
        price: 38,
        category: Category::Clothing,
        ratio: 1.4753,
        photo: include_bytes!("../../../../assets/shrine/31-0.jpg"),
    },
    Product {
        id: 32,
        name: "Classic white collar",
        price: 58,
        category: Category::Clothing,
        ratio: 0.6717,
        photo: include_bytes!("../../../../assets/shrine/32-0.jpg"),
    },
    Product {
        id: 33,
        name: "Cerise scallop tee",
        price: 42,
        category: Category::Clothing,
        ratio: 1.5023,
        photo: include_bytes!("../../../../assets/shrine/33-0.jpg"),
    },
    Product {
        id: 34,
        name: "Shoulder rolls tee",
        price: 27,
        category: Category::Clothing,
        ratio: 0.6687,
        photo: include_bytes!("../../../../assets/shrine/34-0.jpg"),
    },
    Product {
        id: 35,
        name: "Grey slouch tank",
        price: 24,
        category: Category::Clothing,
        ratio: 0.6748,
        photo: include_bytes!("../../../../assets/shrine/35-0.jpg"),
    },
    Product {
        id: 36,
        name: "Sunshirt dress",
        price: 58,
        category: Category::Clothing,
        ratio: 0.6657,
        photo: include_bytes!("../../../../assets/shrine/36-0.jpg"),
    },
    Product {
        id: 37,
        name: "Fine lines tee",
        price: 58,
        category: Category::Clothing,
        ratio: 0.6657,
        photo: include_bytes!("../../../../assets/shrine/37-0.jpg"),
    },
];

/// Everything in a category, or everything at all.
pub fn in_category(category: Option<Category>) -> impl Iterator<Item = &'static Product> {
    PRODUCTS
        .iter()
        .filter(move |product| category.is_none_or(|c| product.category == c))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_catalogue_matches_upstream() {
        assert_eq!(PRODUCTS.len(), 38);
        // "All" plus one per category.
        assert_eq!(CATEGORIES.len(), 4);
    }

    #[test]
    fn filtering_by_category_adds_back_up() {
        let total: usize = CATEGORIES
            .iter()
            .skip(1)
            .map(|c| in_category(*c).count())
            .sum();
        assert_eq!(total, PRODUCTS.len());
        assert_eq!(in_category(None).count(), PRODUCTS.len());
    }

    #[test]
    fn every_product_has_a_photo_and_a_shape() {
        for product in PRODUCTS {
            assert!(!product.photo.is_empty(), "{} has no photo", product.name);
            assert!(product.ratio > 0.0, "{} has no aspect", product.name);
        }
    }
}
