// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//! Corresponds to `lib/demos/cupertino/cupertino_demos.dart` (flutter/gallery
//! @ d12640d).
//!
//! Upstream this file is the export barrel: it re-exports every demo file so
//! the catalogue (`lib/data/demos.dart`) can reference each demo's widget
//! from one import. Here the catalogue (`src/data/demos.rs`, generated by
//! `tools/gen_catalog.py`) references demos by slug only, and the barrel's
//! two jobs are already covered: the `mod` declarations in `mod.rs` are the
//! exports, and `mod.rs`'s `stage()`/`overlay()` dispatch is the resolution.
//! Nothing remains for this file to carry.
