"""Turns upstream's generated Windows key map into the two forms rustflutter
needs: sorted C arrays for the host, and named constants for the framework.

Reads flutter_key_map.g.cc, which is itself generated by
flutter/flutter:dev/tools/gen_keycodes. Rerunning this after an engine roll is
how the tables stay current, and is what keeps the C++ values and the Rust names
from drifting -- they are two views of one table, not two tables.

    python flutter/rust/host/tools/gen_key_map.py \\
        flutter/shell/platform/windows/flutter_key_map.g.cc \\
        flutter/rust/host/rustflutter_key_map_win.cc \\
        flutter/rust/rustflutter/src/keyboard/keys.rs
"""

import re
import sys

SRC = sys.argv[1]
CC_OUT = sys.argv[2]
RS_OUT = sys.argv[3]

text = open(SRC, encoding="utf-8").read()

ENTRY = re.compile(r"\{(0x[0-9a-f]+),\s*(0x[0-9a-f]+)\},\s*//\s*(.*)")


def table(name):
    start = text.index(name)
    end = text.index("};", start)
    out = []
    for m in ENTRY.finditer(text[start:end]):
        out.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))
    return out


physical = table("windowsToPhysicalMap_")
logical = table("windowsToLogicalMap_")
scan_logical = table("scanCodeToLogicalMap_")

print(f"physical {len(physical)}  logical {len(logical)}  scan->logical {len(scan_logical)}")


# -- the C++ side ------------------------------------------------------------

def emit_cc(name, rows):
    lines = [f"constexpr KeyMapping k{name}[] = {{"]
    for key, value, comment in sorted(rows):
        lines.append(f"    {{0x{key:08x}, 0x{value:011x}}},  // {comment}")
    lines.append("};")
    return "\n".join(lines)


cc = f"""// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Scan codes and virtual keys to Flutter's physical and logical key values.
//
// GENERATED -- see rust/host/tools/gen_key_map.py. The data is upstream's
// shell/platform/windows/flutter_key_map.g.cc, which gen_keycodes.dart
// generates from the same source as the framework's key definitions. It is
// reshaped here into sorted arrays: the upstream file defines them as static
// std::map members of KeyboardKeyEmbedderHandler, a class this host does not
// link, and three maps built at static-initialisation time is a cost with
// nothing to show for it when a binary search over constant data does.

#include "flutter/rust/host/rustflutter_key_map_win.h"

#include <algorithm>

namespace flutter {{
namespace {{

struct KeyMapping {{
  uint32_t from;
  uint64_t to;
}};

{emit_cc("ScanCodeToPhysical", physical)}

{emit_cc("VirtualKeyToLogical", logical)}

// Keys whose virtual key code is ambiguous or zero, and so have to be told
// apart by where they are on the keyboard rather than by what they report.
{emit_cc("ScanCodeToLogical", scan_logical)}

/// Binary search over a table sorted by `from`. Returns `fallback` when absent.
template <size_t N>
uint64_t Lookup(const KeyMapping (&table)[N], uint32_t from, uint64_t fallback) {{
  const KeyMapping* end = table + N;
  const KeyMapping* found = std::lower_bound(
      table, end, from,
      [](const KeyMapping& entry, uint32_t value) {{ return entry.from < value; }});
  return (found != end && found->from == from) ? found->to : fallback;
}}

/// Chromium's scan code convention, which the tables above are keyed by: the
/// extended-key flag becomes the 0xe000 bit, so PageUp is 0xe049 rather than
/// 0x49 plus a bool.
uint32_t NormalizeScanCode(uint16_t scan_code, bool extended) {{
  return (scan_code & 0xff) | (extended ? 0xe000 : 0);
}}

}}  // namespace

uint64_t PhysicalKeyForScanCode(uint16_t scan_code, bool extended) {{
  const uint32_t normalized = NormalizeScanCode(scan_code, extended);
  // A key with no entry keeps its scan code, in the Windows plane. That is a
  // stable identity even though nothing can name it, which is what physical
  // keys are for.
  return Lookup(kScanCodeToPhysical, normalized,
                (scan_code & kValueMask) | kWindowsPlane);
}}

uint64_t LogicalKeyForVirtualKey(uint32_t virtual_key,
                                 uint16_t scan_code,
                                 bool extended) {{
  const uint32_t normalized = NormalizeScanCode(scan_code, extended);

  // Position first: the numeric keypad and the right-hand modifiers report the
  // same virtual key as their counterparts elsewhere on the keyboard.
  const uint64_t by_position = Lookup(kScanCodeToLogical, normalized, 0);
  if (by_position != 0) {{
    return by_position;
  }}

  const uint64_t by_key = Lookup(kVirtualKeyToLogical, virtual_key, 0);
  if (by_key != 0) {{
    return by_key;
  }}

  // Letters and digits are not in the table: their logical value is the
  // character itself, lower-cased, in the Unicode plane. `A` and `a` are the
  // same key and must be the same logical value.
  if (virtual_key >= 0x20 && virtual_key <= 0xff) {{
    uint32_t lowered = virtual_key;
    if (lowered >= 'A' && lowered <= 'Z') {{
      lowered += 'a' - 'A';
    }}
    return lowered;
  }}

  return (virtual_key & kValueMask) | kWindowsPlane;
}}

}}  // namespace flutter
"""

open(CC_OUT, "w", encoding="utf-8", newline="\n").write(cc)


# -- the Rust side -----------------------------------------------------------

def camel(name):
    """`arrowLeft` -> `ARROW_LEFT`, `f11` -> `F11`, `keyQ` -> `KEY_Q`."""
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not (name[i - 1].isupper()):
            out.append("_")
        out.append(ch.upper())
    return "".join(out)


def rust_consts(rows, kind, arrow):
    seen = {}
    order = []
    for _key, value, comment in rows:
        name = comment.split(arrow)[-1].strip() if arrow else comment.strip()
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name):
            continue
        ident = camel(name)
        if ident in seen:
            continue
        seen[ident] = value
        order.append((ident, value, name))
    return order


phys_consts = rust_consts(physical, "PhysicalKey", None)
log_consts = rust_consts(logical, "LogicalKey", "->")

# The letters and digits, whose logical value is the character itself. They are
# not in the table because the rule that produces them is arithmetic.
for ch in "abcdefghijklmnopqrstuvwxyz":
    log_consts.append((f"KEY_{ch.upper()}", ord(ch), ch))
for ch in "0123456789":
    log_consts.append((f"DIGIT_{ch}", ord(ch), ch))

lines = []
lines.append("// Copyright 2013 The Flutter Authors. All rights reserved.")
lines.append("// Use of this source code is governed by a BSD-style license that can be")
lines.append("// found in the LICENSE file.")
lines.append("")
lines.append("//! Names for the key values the host sends up.")
lines.append("//!")
lines.append("//! GENERATED -- see `rust/host/tools/gen_key_map.py`. Both sets come from the")
lines.append("//! same upstream table the C++ side is built from, so a name here and a value")
lines.append("//! there cannot drift apart. Upstream these are `PhysicalKeyboardKey` and")
lines.append("//! `LogicalKeyboardKey` in `packages/flutter/lib/src/services/keyboard_key.g.dart`.")
lines.append("")
lines.append("use super::{LogicalKey, PhysicalKey};")
lines.append("")
lines.append("/// Where the key is on the keyboard, regardless of layout. USB HID usage codes.")
lines.append("impl PhysicalKey {")
for ident, value, name in phys_consts:
    lines.append(f"    /// `{name}`")
    lines.append(f"    pub const {ident}: PhysicalKey = PhysicalKey(0x{value:x});")
lines.append("}")
lines.append("")
lines.append("/// What the key means under the current layout.")
lines.append("impl LogicalKey {")
for ident, value, name in log_consts:
    lines.append(f"    /// `{name}`")
    lines.append(f"    pub const {ident}: LogicalKey = LogicalKey(0x{value:x});")
lines.append("}")
lines.append("")

open(RS_OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print(f"wrote {CC_OUT} and {RS_OUT}: {len(phys_consts)} physical, {len(log_consts)} logical names")
