"""Turns upstream's generated GTK key map into the sorted C arrays the Linux
host binary-searches.

Reads fl_key_mapping.g.cc, which is itself generated by
flutter/flutter:dev/tools/gen_keycodes. Rerunning this after an engine roll is
how the tables stay current. Unlike gen_key_map.py it emits no Rust constants:
the framework's key names are platform-independent and already generated from
the Windows table -- the two hosts feed the same values in.

    python flutter/rust/host/tools/gen_key_map_linux.py \\
        flutter/shell/platform/linux/fl_key_mapping.g.cc \\
        flutter/rust/host/rustflutter_key_map_linux.cc
"""

import re
import sys

SRC = sys.argv[1]
CC_OUT = sys.argv[2]

text = open(SRC, encoding="utf-8").read()

ENTRY = re.compile(r"\{(0x[0-9a-f]+),\s*(0x[0-9a-f]+)\},\s*//\s*(.*)")


def table(name):
    start = text.index(name)
    end = text.index("};", start)
    out = []
    for m in ENTRY.finditer(text[start:end]):
        out.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))
    return out


physical = table("xkb_to_physical_key_map")
logical = table("gtk_keyval_to_logical_key_map")

print(f"physical {len(physical)}  logical {len(logical)}")


def emit_cc(name, rows):
    lines = [f"constexpr KeyMapping k{name}[] = {{"]
    for key, value, comment in sorted(rows):
        lines.append(f"    {{0x{key:08x}, 0x{value:011x}}},  // {comment}")
    lines.append("};")
    return "\n".join(lines)


cc = f"""// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// XKB keycodes and GDK keyvals to Flutter's physical and logical key values.
//
// GENERATED -- see rust/host/tools/gen_key_map_linux.py. The data is
// upstream's shell/platform/linux/fl_key_mapping.g.cc, which
// gen_keycodes.dart generates from the same source as the framework's key
// definitions. It is reshaped here into sorted arrays: the upstream file
// defines them as std::maps built at static-initialisation time, a cost with
// nothing to show for it when a binary search over constant data does.

#include "flutter/rust/host/rustflutter_key_map_linux.h"

#include <algorithm>

namespace flutter {{
namespace {{

struct KeyMapping {{
  uint32_t from;
  uint64_t to;
}};

{emit_cc("XkbToPhysical", physical)}

{emit_cc("KeyvalToLogical", logical)}

/// Binary search over a table sorted by `from`. Returns `fallback` when absent.
template <size_t N>
uint64_t Lookup(const KeyMapping (&table)[N],
                uint32_t from,
                uint64_t fallback) {{
  const KeyMapping* end = table + N;
  const KeyMapping* found = std::lower_bound(
      table, end, from, [](const KeyMapping& entry, uint32_t value) {{
        return entry.from < value;
      }});
  return (found != end && found->from == from) ? found->to : fallback;
}}

}}  // namespace

uint64_t PhysicalKeyForKeycode(uint16_t keycode) {{
  // A key with no entry keeps its keycode, in the GTK plane. That is a stable
  // identity even though nothing can name it, which is what physical keys are
  // for. Upstream's `event_to_physical_key` falls back the same way.
  return Lookup(kXkbToPhysical, keycode, (keycode & kValueMask) | kGtkPlane);
}}

uint64_t LogicalKeyForKeyval(uint32_t keyval, uint32_t code_point) {{
  const uint64_t mapped = Lookup(kKeyvalToLogical, keyval, 0);
  if (mapped != 0) {{
    return mapped;
  }}
  // A key that types is its character, lower-cased, in the Unicode plane.
  // `A` and `a` are the same key and must be the same logical value.
  if (code_point != 0) {{
    return code_point & kValueMask;
  }}
  return (keyval & kValueMask) | kGtkPlane;
}}

}}  // namespace flutter
"""

open(CC_OUT, "w", encoding="utf-8", newline="\n").write(cc)
print(f"wrote {CC_OUT}")
