"""Turns upstream's generated macOS key map into the form rustflutter needs.

The macOS counterpart of gen_key_map.py, and the same argument for existing:
the tables are two views of one table rather than two tables, so a key that
moves upstream moves here by rerunning this rather than by being retyped.

Reads KeyCodeMap.g.mm, which is itself generated by
flutter/flutter:dev/tools/gen_keycodes. The upstream file defines the tables as
`NSDictionary` literals built at static-initialisation time and looked up by
boxing an integer; this host has no Foundation in its hot path and no reason to
pay for either, so they are reshaped into sorted C arrays a binary search reads.

    python flutter/rust/host/tools/gen_key_map_mac.py \\
        flutter/shell/platform/darwin/macos/framework/Source/KeyCodeMap.g.mm \\
        flutter/rust/host/rustflutter_key_map_mac.cc
"""

import re
import sys

SRC = sys.argv[1]
CC_OUT = sys.argv[2]

text = open(SRC, encoding="utf-8").read()

ENTRY = re.compile(r"@(0x[0-9a-f]+)\s*:\s*@(0x[0-9a-f]+),\s*//\s*(.*)")
MODIFIER = re.compile(r"@(0x[0-9a-f]+)\s*:\s*@\((kModifierFlag\w+)\)")


def table(name):
  """The entries of one `@{ ... }` literal, in the order they are written."""
  start = text.index(name)
  end = text.index("};", start)
  body = text[start:end]
  return [(int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip())
          for m in ENTRY.finditer(body)]


def modifier_table(name):
  start = text.index(name)
  end = text.index("};", start)
  body = text[start:end]
  return [(int(m.group(1), 16), m.group(2)) for m in MODIFIER.finditer(body)]


physical = table("keyCodeToPhysicalKey")
logical = table("keyCodeToLogicalKey")
modifiers = modifier_table("keyCodeToModifierFlag")

print("physical %d  logical %d  modifiers %d" %
      (len(physical), len(logical), len(modifiers)))

# The flag names upstream gives its modifier bits, and the AppKit constants
# behind them -- upstream's KeyCodeMap_Internal.h. Left and right are separate
# bits, which NSEvent reports and NSEventModifierFlags does not name.
FLAG_VALUES = {
    "kModifierFlagShiftLeft": 0x0002,
    "kModifierFlagShiftRight": 0x0004,
    "kModifierFlagControlLeft": 0x0001,
    "kModifierFlagControlRight": 0x2000,
    "kModifierFlagAltLeft": 0x0020,
    "kModifierFlagAltRight": 0x0040,
    "kModifierFlagMetaLeft": 0x0008,
    "kModifierFlagMetaRight": 0x0010,
}

HEADER = """// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// macOS virtual key codes to Flutter's physical and logical key values.
//
// GENERATED -- see rust/host/tools/gen_key_map_mac.py. The data is upstream's
// shell/platform/darwin/macos/framework/Source/KeyCodeMap.g.mm, which
// gen_keycodes.dart generates from the same source as the framework's key
// definitions. It is reshaped here into sorted arrays: the upstream file
// defines them as NSDictionary literals built at static-initialisation time and
// read by boxing an integer, and a binary search over constant data does the
// same job without Foundation.

#include "flutter/rust/host/rustflutter_key_map_mac.h"

#include <algorithm>

namespace flutter {
namespace {

struct KeyMapping {
  uint32_t from;
  uint64_t to;
};

"""

FOOTER = """
/// Binary search over a table sorted by `from`. Returns `fallback` when absent.
template <size_t N>
uint64_t Lookup(const KeyMapping (&table)[N], uint32_t from, uint64_t fallback) {
  const KeyMapping* end = table + N;
  const KeyMapping* found = std::lower_bound(
      table, end, from,
      [](const KeyMapping& entry, uint32_t value) { return entry.from < value; });
  return (found != end && found->from == from) ? found->to : fallback;
}

}  // namespace

uint64_t PhysicalKeyForKeyCode(uint16_t key_code) {
  // A key with no entry keeps its macOS identity rather than colliding with a
  // real HID usage. That is a stable identity even though nothing can name it,
  // which is what physical keys are for.
  return Lookup(kKeyCodeToPhysical, key_code, (key_code & kValueMask) | kMacosPlane);
}

uint64_t LogicalKeyForKeyCode(uint16_t key_code, uint32_t character) {
  // The named keys first: enter, the arrows, the function row and both of every
  // modifier. Their meaning does not depend on the layout.
  const uint64_t named = Lookup(kKeyCodeToLogical, key_code, 0);
  if (named != 0) {
    return named;
  }

  // Everything else is a character key, and its logical value is the character
  // it produces with no modifiers applied, lower-cased, in the Unicode plane.
  // `A` and `a` are the same key and must be the same logical value -- which is
  // why the caller passes `charactersIgnoringModifiers` rather than
  // `characters`.
  if (character != 0) {
    uint32_t lowered = character;
    if (lowered >= 'A' && lowered <= 'Z') {
      lowered += 'a' - 'A';
    }
    return static_cast<uint64_t>(lowered) | kUnicodePlane;
  }

  return (key_code & kValueMask) | kMacosPlane;
}

uint64_t ModifierFlagForKeyCode(uint16_t key_code) {
  return Lookup(kKeyCodeToModifierFlag, key_code, 0);
}

}  // namespace flutter
"""


def emit(name, rows, width=11):
  out = ["constexpr KeyMapping %s[] = {\n" % name]
  for source, target, comment in sorted(rows, key=lambda row: row[0]):
    out.append("    {0x%08x, 0x%0*x},  // %s\n" % (source, width, target, comment))
  out.append("};\n\n")
  return "".join(out)


with open(CC_OUT, "w", encoding="utf-8", newline="\n") as out:
  out.write(HEADER)
  out.write(emit("kKeyCodeToPhysical", physical))
  out.write(emit("kKeyCodeToLogical", logical))
  out.write(
      emit(
          "kKeyCodeToModifierFlag",
          [(code, FLAG_VALUES[flag], flag[len("kModifierFlag"):])
           for code, flag in modifiers],
          width=4,
      ))
  out.write(FOOTER)

print("wrote %s" % CC_OUT)
