"""Turns upstream's generated Windows key map into the two forms rustflutter
needs: sorted C arrays for the host, and named constants for the framework.

Reads flutter_key_map.g.cc, which is itself generated by
flutter/flutter:dev/tools/gen_keycodes. Rerunning this after an engine roll is
how the tables stay current, and is what keeps the C++ values and the Rust names
from drifting -- they are two views of one table, not two tables.

The **names** take more sources than the Windows arrays do. Those arrays are
what the Windows host looks a Windows key up in, so they are the Windows table
and nothing else; the Rust constants are what an application binds a shortcut
to, and an application runs on every host. GTK sends logical values Windows
never does -- `KP_Enter`, Copy, Paste, Redo, Super -- and Android sends a whole
game controller. A value with no name is a key nothing can bind, so the fourth
and fifth arguments are read for their logical values as well.

The fifth argument also produces a table of its own,
`rustflutter_key_map_android.cc`, written beside the Windows one: Android
identifies a key from two numbers that Windows does not use.

    python flutter/rust/host/tools/gen_key_map.py \\
        flutter/shell/platform/windows/flutter_key_map.g.cc \\
        flutter/rust/host/rustflutter_key_map_win.cc \\
        flutter/rust/rustflutter/src/keyboard/keys.rs \\
        flutter/shell/platform/linux/fl_key_mapping.g.cc \\
        flutter/shell/platform/android/io/flutter/embedding/android/KeyboardMap.java
"""

import os
import re
import sys

SRC = sys.argv[1]
CC_OUT = sys.argv[2]
RS_OUT = sys.argv[3]

text = open(SRC, encoding="utf-8").read()

ENTRY = re.compile(r"\{(0x[0-9a-f]+),\s*(0x[0-9a-f]+)\},\s*//\s*(.*)")


def table(name):
    start = text.index(name)
    end = text.index("};", start)
    out = []
    for m in ENTRY.finditer(text[start:end]):
        out.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))
    return out


physical = table("windowsToPhysicalMap_")
logical = table("windowsToLogicalMap_")
scan_logical = table("scanCodeToLogicalMap_")

# Logical values only, from the other hosts. Their comments are the upstream
# key names on the left-hand side (`KP_Enter`), so the name for the constant
# comes from the value rather than from the comment -- see `gtk_names`.
GTK_SRC = sys.argv[4] if len(sys.argv) > 4 else None
gtk_logical = []
if GTK_SRC:
    gtk_text = open(GTK_SRC, encoding="utf-8").read()
    start = gtk_text.index("gtk_keyval_to_logical_key_map")
    end = gtk_text.index("};", start)
    for m in ENTRY.finditer(gtk_text[start:end]):
        gtk_logical.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))

# The Android tables, from upstream's KeyboardMap.java -- generated by the same
# gen_keycodes.dart run as the Windows file, so it is the same data seen from
# Android's side rather than a second source of truth. Java spells its entries
# `put(0x3eL, 0x20L); // space`, which is why it needs its own pattern.
#
# Android names a key twice, as every platform does, but from two different
# numbers: `KeyEvent.getScanCode()` is the Linux evdev code and gives the
# physical key, `KeyEvent.getKeyCode()` is Android's own and gives the logical
# one. They are not two views of one table -- a keyCode is a meaning, a
# scanCode is a place -- so neither can stand in for the other.
ANDROID_SRC = sys.argv[5] if len(sys.argv) > 5 else None
JAVA_ENTRY = re.compile(r"put\((0x[0-9a-f]+)L,\s*(0x[0-9a-f]+)L\);\s*//\s*(.*)")
android_physical = []
android_logical = []
if ANDROID_SRC:
    java_text = open(ANDROID_SRC, encoding="utf-8").read()

    def java_table(name):
        start = java_text.index(name)
        end = java_text.index("      };", start)
        out = []
        for m in JAVA_ENTRY.finditer(java_text[start:end]):
            out.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()))
        return out

    android_physical = java_table("scanCodeToPhysical")
    android_logical = java_table("keyCodeToLogical")
    print(f"android scan->physical {len(android_physical)}  "
          f"keycode->logical {len(android_logical)}")

print(f"physical {len(physical)}  logical {len(logical)}  scan->logical {len(scan_logical)}")


# -- the C++ side ------------------------------------------------------------

def emit_cc(name, rows):
    lines = [f"constexpr KeyMapping k{name}[] = {{"]
    for key, value, comment in sorted(rows):
        lines.append(f"    {{0x{key:08x}, 0x{value:011x}}},  // {comment}")
    lines.append("};")
    return "\n".join(lines)


cc = f"""// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Scan codes and virtual keys to Flutter's physical and logical key values.
//
// GENERATED -- see rust/host/tools/gen_key_map.py. The data is upstream's
// shell/platform/windows/flutter_key_map.g.cc, which gen_keycodes.dart
// generates from the same source as the framework's key definitions. It is
// reshaped here into sorted arrays: the upstream file defines them as static
// std::map members of KeyboardKeyEmbedderHandler, a class this host does not
// link, and three maps built at static-initialisation time is a cost with
// nothing to show for it when a binary search over constant data does.

#include "flutter/rust/host/rustflutter_key_map_win.h"

#include <algorithm>

namespace flutter {{
namespace {{

struct KeyMapping {{
  uint32_t from;
  uint64_t to;
}};

{emit_cc("ScanCodeToPhysical", physical)}

{emit_cc("VirtualKeyToLogical", logical)}

// Keys whose virtual key code is ambiguous or zero, and so have to be told
// apart by where they are on the keyboard rather than by what they report.
{emit_cc("ScanCodeToLogical", scan_logical)}

/// Binary search over a table sorted by `from`. Returns `fallback` when absent.
template <size_t N>
uint64_t Lookup(const KeyMapping (&table)[N],
                uint32_t from,
                uint64_t fallback) {{
  const KeyMapping* end = table + N;
  const KeyMapping* found = std::lower_bound(
      table, end, from, [](const KeyMapping& entry, uint32_t value) {{
        return entry.from < value;
      }});
  return (found != end && found->from == from) ? found->to : fallback;
}}

/// Chromium's scan code convention, which the tables above are keyed by: the
/// extended-key flag becomes the 0xe000 bit, so PageUp is 0xe049 rather than
/// 0x49 plus a bool.
uint32_t NormalizeScanCode(uint16_t scan_code, bool extended) {{
  return (scan_code & 0xff) | (extended ? 0xe000 : 0);
}}

}}  // namespace

uint64_t PhysicalKeyForScanCode(uint16_t scan_code, bool extended) {{
  const uint32_t normalized = NormalizeScanCode(scan_code, extended);
  // A key with no entry keeps its scan code, in the Windows plane. That is a
  // stable identity even though nothing can name it, which is what physical
  // keys are for.
  return Lookup(kScanCodeToPhysical, normalized,
                (scan_code & kValueMask) | kWindowsPlane);
}}

uint64_t LogicalKeyForVirtualKey(uint32_t virtual_key,
                                 uint16_t scan_code,
                                 bool extended) {{
  const uint32_t normalized = NormalizeScanCode(scan_code, extended);

  // Position first: the numeric keypad and the right-hand modifiers report the
  // same virtual key as their counterparts elsewhere on the keyboard.
  const uint64_t by_position = Lookup(kScanCodeToLogical, normalized, 0);
  if (by_position != 0) {{
    return by_position;
  }}

  const uint64_t by_key = Lookup(kVirtualKeyToLogical, virtual_key, 0);
  if (by_key != 0) {{
    return by_key;
  }}

  // Letters and digits are not in the table: their logical value is the
  // character itself, lower-cased, in the Unicode plane. `A` and `a` are the
  // same key and must be the same logical value.
  if (virtual_key >= 0x20 && virtual_key <= 0xff) {{
    uint32_t lowered = virtual_key;
    if (lowered >= 'A' && lowered <= 'Z') {{
      lowered += 'a' - 'A';
    }}
    return lowered;
  }}

  return (virtual_key & kValueMask) | kWindowsPlane;
}}

}}  // namespace flutter
"""

open(CC_OUT, "w", encoding="utf-8", newline="\n").write(cc)


# -- the Android side --------------------------------------------------------

def dedupe(rows):
    """Last `put` wins, which is what a Java HashMap does.

    The binary search below needs each `from` once and in order; a duplicated
    key would make which entry it finds depend on the search rather than on
    the table.
    """
    latest = {}
    for key, value, comment in rows:
        latest[key] = (key, value, comment)
    return sorted(latest.values())


if ANDROID_SRC:
    ANDROID_OUT = CC_OUT.replace("_win.cc", "_android.cc")
    assert ANDROID_OUT != CC_OUT, CC_OUT
    android_cc = f"""// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Android key codes and scan codes to Flutter's physical and logical key
// values.
//
// GENERATED -- see rust/host/tools/gen_key_map.py. The data is upstream's
// shell/platform/android/io/flutter/embedding/android/KeyboardMap.java, which
// gen_keycodes.dart generates from the same source as the framework's key
// definitions and as the Windows table next door.
//
// Upstream reads these maps in Java, from KeyEmbedderResponder. This host maps
// in C++ instead, for the same reason the JNI layer is thin everywhere else:
// the Java side of this port is an Activity and nothing more, and a table that
// lives beside the Windows one is a table that gets regenerated with it.
//
// This file is compiled on every platform, not only Android. It names no
// Android header and reaches for nothing -- it is arithmetic over constant
// data -- and building it everywhere is what lets the host test binary check
// it on a desktop, which is the only place these tests are ever run.

#include "flutter/rust/host/rustflutter_key_map_android.h"

#include <algorithm>

namespace flutter {{
namespace {{

struct KeyMapping {{
  uint32_t from;
  uint64_t to;
}};

// The low bits a key value can occupy. See the header for why this one is not
// declared there beside kAndroidPlane.
constexpr uint64_t kValueMask = 0x000ffffffff;

// Linux evdev scan codes, which is what `KeyEvent.getScanCode()` returns.
{emit_cc("AndroidScanCodeToPhysical", dedupe(android_physical))}

// Android's own key codes, which is what `KeyEvent.getKeyCode()` returns.
{emit_cc("AndroidKeyCodeToLogical", dedupe(android_logical))}

/// Binary search over a table sorted by `from`. Returns `fallback` when absent.
template <size_t N>
uint64_t Lookup(const KeyMapping (&table)[N],
                uint32_t from,
                uint64_t fallback) {{
  const KeyMapping* end = table + N;
  const KeyMapping* found = std::lower_bound(
      table, end, from, [](const KeyMapping& entry, uint32_t value) {{
        return entry.from < value;
      }});
  return (found != end && found->from == from) ? found->to : fallback;
}}

/// A key nothing can name keeps the number the platform gave it, moved into
/// Android's plane so it cannot collide with a real Unicode codepoint or with
/// another platform's unnamed key.
uint64_t KeyOfAndroidPlane(uint32_t key) {{
  return kAndroidPlane | (key & kValueMask);
}}

}}  // namespace

uint64_t PhysicalKeyForAndroidKey(uint32_t scan_code, uint32_t key_code) {{
  // A scan code of zero is not a key at the top of the keyboard: it is a key
  // that never came from a keyboard. `adb shell input keyevent` produces
  // exactly this, and so does an emulator, and the two keys under test would
  // otherwise share one physical value and cancel each other's press. The key
  // code cannot also be zero -- `KEYCODE_UNKNOWN` events are dropped before
  // this -- so it is what tells them apart.
  if (scan_code == 0) {{
    return KeyOfAndroidPlane(key_code);
  }}
  return Lookup(kAndroidScanCodeToPhysical, scan_code,
                KeyOfAndroidPlane(scan_code));
}}

uint64_t LogicalKeyForAndroidKeyCode(uint32_t key_code) {{
  return Lookup(kAndroidKeyCodeToLogical, key_code,
                KeyOfAndroidPlane(key_code));
}}

}}  // namespace flutter
"""
    open(ANDROID_OUT, "w", encoding="utf-8", newline="\n").write(android_cc)
    print(f"wrote {ANDROID_OUT}")


# -- the Rust side -----------------------------------------------------------

def camel(name):
    """`arrowLeft` -> `ARROW_LEFT`, `f11` -> `F11`, `keyQ` -> `KEY_Q`."""
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not (name[i - 1].isupper()):
            out.append("_")
        out.append(ch.upper())
    return "".join(out)


def rust_consts(rows, kind, arrow):
    seen = {}
    order = []
    for _key, value, comment in rows:
        name = comment.split(arrow)[-1].strip() if arrow else comment.strip()
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name):
            continue
        ident = camel(name)
        if ident in seen:
            continue
        seen[ident] = value
        order.append((ident, value, name))
    return order


phys_consts = rust_consts(physical, "PhysicalKey", None)
log_consts = rust_consts(logical, "LogicalKey", "->")

# The four sided-modifier synonyms. No host sends them -- a keyboard always
# reports a side -- so they are in no map, and they were hand-written into this
# generated file until the generator started overwriting them. They belong
# here: a *shortcut* usually does not care which Shift was pressed, and
# upstream spells the same four in `keyboard_key.g.dart`.
SYNONYMS = [
    ("CONTROL", 0x2000001F0, "control"),
    ("SHIFT", 0x2000001F2, "shift"),
    ("ALT", 0x2000001F4, "alt"),
    ("META", 0x2000001F6, "meta"),
]
log_consts.extend(SYNONYMS)

# The letters and digits, whose logical value is the character itself. They are
# not in the table because the rule that produces them is arithmetic.
#
# These come **before** the by-value merge below, not after, and that ordering
# is the whole of what stops `KEY_A` being declared twice: Android's table does
# name its letters and digits, so a merge that ran first would emit `DIGIT0`
# beside the `DIGIT_0` these lines produce -- one value under two names, which
# is where drift starts -- and a second `KEY_A`, which does not even compile.
for ch in "abcdefghijklmnopqrstuvwxyz":
    log_consts.append((f"KEY_{ch.upper()}", ord(ch), ch))
for ch in "0123456789":
    log_consts.append((f"DIGIT_{ch}", ord(ch), ch))

# The GTK comments are X11 key names (`KP_Enter`, `3270_Copy`), not Flutter's,
# so the name comes from upstream's own `keyboard_key.g.dart` by value. A value
# that is not in that file has no upstream name either and is left unnamed --
# better an unnamed value than one this script invented.
if gtk_logical:
    upstream_names = {}
    dart = os.path.join(
        os.path.dirname(SRC), "..", "..", "..", "..",
        "flutter", "packages", "flutter", "lib", "src", "services",
        "keyboard_key.g.dart",
    )
    dart = os.environ.get("FLUTTER_KEYBOARD_KEY_DART", dart)
    if os.path.exists(dart):
        for m in re.finditer(
            r"static const LogicalKeyboardKey (\w+) = LogicalKeyboardKey\(0x([0-9a-f]+)\)",
            open(dart, encoding="utf-8").read(),
        ):
            upstream_names.setdefault(int(m.group(2), 16), m.group(1))
    named = {value for _ident, value, _name in log_consts}
    # Android's comments *are* Flutter's names (`gameButtonA`), unlike GTK's,
    # but they go through the same by-value lookup anyway: one rule for where a
    # name comes from is easier to trust than two, and a value upstream does
    # not name is one this script must not name either.
    for _code, value, _comment in sorted(gtk_logical + android_logical,
                                         key=lambda row: row[1]):
        if value in named or value not in upstream_names:
            continue
        name = upstream_names[value]
        log_consts.append((camel(name), value, name))
        named.add(value)

# Said once, at the end, about every name however it got here: a value with two
# names is a bug this file cannot express, and an identifier twice over does not
# compile. The check is cheap and the failure it catches is silent -- the
# generator would happily write either.
by_value = {}
by_ident = {}
for ident, value, _name in log_consts:
    assert value not in by_value, f"{ident} and {by_value[value]} are both 0x{value:x}"
    assert ident not in by_ident, f"{ident} declared twice"
    by_value[value] = ident
    by_ident[ident] = value

lines = []
lines.append("// Copyright 2013 The Flutter Authors. All rights reserved.")
lines.append("// Use of this source code is governed by a BSD-style license that can be")
lines.append("// found in the LICENSE file.")
lines.append("")
lines.append("//! Names for the key values the host sends up.")
lines.append("//!")
lines.append("//! GENERATED -- see `rust/host/tools/gen_key_map.py`. Both sets come from the")
lines.append("//! same upstream table the C++ side is built from, so a name here and a value")
lines.append("//! there cannot drift apart. Upstream these are `PhysicalKeyboardKey` and")
lines.append("//! `LogicalKeyboardKey` in `packages/flutter/lib/src/services/keyboard_key.g.dart`.")
lines.append("")
lines.append("use super::{LogicalKey, PhysicalKey};")
lines.append("")
lines.append("/// Where the key is on the keyboard, regardless of layout. USB HID usage codes.")
lines.append("impl PhysicalKey {")
for ident, value, name in phys_consts:
    lines.append(f"    /// `{name}`")
    lines.append(f"    pub const {ident}: PhysicalKey = PhysicalKey(0x{value:x});")
lines.append("}")
lines.append("")
lines.append("/// What the key means under the current layout.")
lines.append("impl LogicalKey {")
for ident, value, name in log_consts:
    lines.append(f"    /// `{name}`")
    lines.append(f"    pub const {ident}: LogicalKey = LogicalKey(0x{value:x});")
lines.append("}")
lines.append("")

open(RS_OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print(f"wrote {CC_OUT} and {RS_OUT}: {len(phys_consts)} physical, {len(log_consts)} logical names")
